print("------------------------------------")
print("-- Loading hell2 file             --")
print("------------------------------------")
print("-- [Loading] ctrl.lua")

function config(map)
	MapCanSavePos(map, 0)			-- 1 = Allow players to save respawn // 0 = Do not allow players to save respawn
	MapCanPK(map, 1)				-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
	MapCopyNum(map, 1)				-- 1 Copy of the map will be generated by GameServer
	SingleMapCopyPlyNum(map, 300)	-- 300 Players are allowed to enter the map
	MapCanTeam(map, 1)				-- 1 = Allow players to create party // 0 = Do not allow players to create party
	MapType(map, 4)					-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )        
    MapCanStall(map, 0)				-- 1 = Allow players to set stall // 0 = Do not allow players to set stall
	--ShowInPortalTimer(map, LUA_TRUE, 72,179)
end

function get_map_entry_pos_hell2()
	return 72,179
end

function init_entry(map)
	SetMapEntryMapName(map, "hell")
	SetMapEntryTime(map, "2006/10/18/6/0", "0/12/0", "0/0/60", "0/0/60") -- official
end

function after_enter_hell2(role, map_copy)
	SystemNotice(role, "Mysterious voice: "..GetChaDefaultName(role)..", not bad to be able to survive till here. If you can cross the water in front, I'll acknowledge your capabilities!") 
end

function before_leave_hell2(role)
end

function map_copy_first_run_hell2(map_copy)
end

function map_copy_run_hell2(map_copy)
	if CheckMonsterDead(AZRAEL[9]) == 1 then
		if CRY[9] == 0 then
			local Notice_all = "Kuroo: The ancient curse has already activated. You will awaken the most deepest evil when you pass through. May death bring you peace!!!"
			MapCopyNotice(map_copy, Notice_all)
			CRY[9] = 1
		end
	end
end

function map_copy_run_special_hell2(map)
end

function map_run_hell2(map)
end

function map_copy_close_hell2(map_copy)
	ClearAllSubMapCha(map_copy)
	--ClearAllSubMapMonster(map_copy)
end

function map_copy_before_close_hell2(map)
end

function can_open_entry_hell2(map)
local Hour = GetNowTime()
if Hour == 6 or Hour == 18 then
    return 1  -- Map is open
end
return 0  -- Map is closed
end
