print("------------------------------------")
print("-- Loading hell4 file             --")
print("------------------------------------")
print("-- [Loading] ctrl.lua")

function config(map)
	MapCanSavePos(map, 0)			-- 1 = Allow players to save respawn // 0 = Do not allow players to save respawn
	MapCanPK(map, 1)				-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
	MapCopyNum(map, 1)				-- 1 Copy of the map will be generated by GameServer
	SingleMapCopyPlyNum(map, 300)	-- 300 Players are allowed to enter the map
	MapCanTeam(map, 1)				-- 1 = Allow players to create party // 0 = Do not allow players to create party
	MapType(map, 4)					-- PvP settings
    MapCanStall(map, 0)				-- 1 = Allow players to set stall // 0 = Do not allow players to set stall
end

function get_map_entry_pos_hell4()
	return 191,180
end

function init_entry(map)
    SetMapEntryMapName(map, "hell3")
	SetMapEntryTime(map, "2006/10/18/6/0", "0/12/0", "0/0/60", "0/0/60") -- official
end

function after_enter_hell4(role, map_copy)
	SystemNotice(role, "Mysterious voice: "..GetChaDefaultName(role)..", I will let you behold the real power of Death!") 
end

function before_leave_hell4(role)
end

function map_copy_first_run_hell4(map_copy)
end

function map_copy_run_hell4(map_copy)
	if CheckMonsterDead(AZRAEL[18]) == 1 then
		if CRY[18] == 0 then
			local Notice_all = "Fifth floor Guard: Foolish humans, Death has granted us the power of immortality. We will meet again. Wahahaha!!!"
			MapCopyNotice(map_copy, Notice_all)
			CRY[18] = 1
			BOSSXYSJ[987] = 4	
			BOSSSJSJ[987] = 4	
			BOSSTJSJ[987] = 4	
			BOSSXZSJ[987] = 4	
			BOSSAYSJ[987] = 4
		end
	end

	if CRY[18] == 1 then
		-- Removed HELLCLOSETIME related code
	end
end

function map_copy_run_special_hell4(map)
end

function map_run_hell4(map)
end

function map_copy_close_hell4(map_copy)
ClearAllSubMapCha(map_copy)
--ClearAllSubMapMonster(map_copy)
end

function map_copy_before_close_hell4(map_copy)
end

function can_open_entry_hell4(map)
local Hour = GetNowTime()
if Hour == 6 or Hour == 18 then
    return 1  -- Map is open
end
return 0  -- Map is closed
end
