print("------------------------------------")
print("-- Loading Dream Pk file            --")
print("------------------------------------")
print("-- [Loading] ctrl.lua")

function config(map)
   	MapCanSavePos(map, 0)			-- 1 = Allow players to save respaw // 0 = Do not allow players to save respaw
	MapCanPK(map, 1)				-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
	MapCopyNum(map, 1)				-- 1 Copy of the map will be generated by GameServer
	SingleMapCopyPlyNum(map, 300)	-- 300 Players are allowed to enter the map
	MapCanTeam(map , 1)				-- 1 = Allow players to create party // 0 = Do not allow players to create party
	MapType(map, 4)					-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )        
    MapCanStall(map, 0)				-- 1 = Allow players to set stall // 0 = Do not allow players to set stall
	ShowInPortalTimer(map, LUA_TRUE, 282,373)
end


function get_map_entry_pos_dreampk()
	return 282,373
end

function init_entry(map)
    SetMapEntryMapName(map, "lobbycityafk2")
   SetMapEntryTime(map, "2006/10/18/3/0", "0/12/0", "0/0/30", "0/0/45")
end

function dreampk_Init()
    PANEL_PLAYER_KILL_COUNT["dreampk"] = {}
    PANEL_PLAYER_DEATH_COUNT["dreampk"] = {}
	PANEL_LAST_PLAYER_KILLED["dreampk"] = {}
	dreampk_Active_Player = 0
	dreampk_Money = 10000000
	dreampk_Wave1 = 0
	dreampk_Wave2 = 0
	dreampk_Wave3 = 0
	dreampk_Wave4 = 0
	dreampk_Wave5 = 0
	dreampk_Wave6 = 0
	dreampk_Wave7 = 0
	dreampk_Tick = 300
	--dreampk_GuildLog = {}
end
dreampk_Init()

function after_enter_dreampk( Player , map_copy )
	Restriction.Add(Player, 'dreampk', 'MAC')
	-- local GuildID = GetChaGuildID(Player)
	-- if GuildID ~= 0 then
		-- dreampk_GuildLog[GuildID] = dreampk_GuildLog[GuildID] or 0
		-- dreampk_GuildLog[GuildID] = dreampk_GuildLog[GuildID] + 1
	-- else 
		-- dreampk_GuildLog[0] = dreampk_GuildLog[0] or 0
		-- dreampk_GuildLog[0] = dreampk_GuildLog[0] + 1
	-- end
end
function before_leave_dreampk( Player )
	Notice(GetChaDefaultName(Player)..' has left Chaos Dream!')
	Restriction.Rem(Player, 'dreampk', 'MAC')
	--BeforeLeaveZone(Player)
	
	--hide playerpanel out o fca
	UpdateTeamPointsPanel(Player, "hide")
	
	-- local GuildID = GetChaGuildID(Player)
	-- if GuildID ~= 0 then
		-- dreampk_GuildLog[GuildID] = dreampk_GuildLog[GuildID] or 0
		-- dreampk_GuildLog[GuildID] = dreampk_GuildLog[GuildID] - 1
		
		-- if dreampk_GuildLog[GuildID] <= 0 then
			-- dreampk_GuildLog[GuildID] = nil
		-- end
		-- else 
		-- dreampk_GuildLog[0] = dreampk_GuildLog[0] or 0
		-- dreampk_GuildLog[0] = dreampk_GuildLog[0] - 1
		
		-- if dreampk_GuildLog[0] <= 0 then
			-- dreampk_GuildLog[0] = nil
		-- end
	-- end
end
function map_copy_first_run_dreampk( map_copy )
	
end
function map_copy_run_dreampk( map_copy )
local Survivor = GetMapActivePlayer(map_copy)
	local MapName = "Chaos Dream"
	SetMapEntryEventName(PortalEntryData8.dreampk, ""..MapName.." | [ "..Survivor.." ] Survivor(s)")
	local Hour = tonumber(os.date("%H"))
	local Minute = tonumber(os.date("%M"))
	local Second = tonumber(os.date("%S"))
	local Message = "Chaos Dream still have survivor(s): "..Survivor.." player(s)!"
	--ScrollNotice ("Chaos Dream still have survivor(s): "..Survivor.." player(s)!",1, 0XFFF6E58D)
	DealAllPlayerInMap(map_copy,"dreampkUpdateKdrPanel")
	if Hour == 3 or Hour == 15 then
		if Minute == 5 and Second == 0 then
		GMNotice(Message)
			if dreampk_Wave1 == 0 then
				local Monster2	= CreateChaEx(859, 10775, 11125, 145, 180, map_copy)
				local Monster3	= CreateChaEx(859, 12725, 11050, 145, 180, map_copy)
				local Monster4	= CreateChaEx(859, 13025, 13100, 145, 180, map_copy)
				local Monster5	= CreateChaEx(859, 10650, 13200, 145, 180, map_copy)
				local Monster6	= CreateChaEx(859, 5550, 11950, 145, 180, map_copy)
				local Monster7	= CreateChaEx(859, 6650, 17825, 145, 180, map_copy)
				local Monster8	= CreateChaEx(859, 11975, 18225, 145, 180, map_copy)
				local Monster9	= CreateChaEx(859, 17475, 17900, 145, 180, map_copy)
				local Monster10	= CreateChaEx(859, 18325, 12025, 145, 180, map_copy)
				local Monster11	= CreateChaEx(859, 17200, 6400, 145, 180, map_copy)
				local Monster12	= CreateChaEx(859, 12050, 5600, 145, 180, map_copy)
				local Monster13 = CreateChaEx(859, 6775, 6350, 145, 180, map_copy)
				local Monster14 = CreateChaEx(859, 4400, 4300, 145, 180, map_copy)
				local Monster15 = CreateChaEx(859, 1925, 4400, 145, 180, map_copy)
				SetChaLifeTime(Monster2, 299050)
				SetChaLifeTime(Monster3, 299100)
				SetChaLifeTime(Monster4, 299150)
				SetChaLifeTime(Monster5, 299200)
				SetChaLifeTime(Monster6, 299250)
				SetChaLifeTime(Monster7, 299300)
				SetChaLifeTime(Monster8, 299350)
				SetChaLifeTime(Monster9, 299400)
				SetChaLifeTime(Monster10, 299450)
				SetChaLifeTime(Monster11, 299500)
				SetChaLifeTime(Monster12, 299550)
				SetChaLifeTime(Monster13, 299600)
				SetChaLifeTime(Monster14, 299650)
				SetChaLifeTime(Monster15, 299700)
				--GMNotice(Message)
				dreampk_Wave1 = dreampk_Wave1 + 1
			end
		end
		if Minute == 10 and Second == 0 then
		GMNotice(Message)
			if dreampk_Wave2 == 0 then
				local Monster16 = CreateChaEx(860, 6550, 11975, 145, 180, map_copy)
				local Monster17 = CreateChaEx(860, 12050, 18250, 145, 180, map_copy)
				local Monster18 = CreateChaEx(860, 17325, 12050, 145, 180, map_copy)
				local Monster19 = CreateChaEx(860, 12025, 5975, 145, 180, map_copy)
				local Monster20 = CreateChaEx(860, 11150, 11225, 145, 180, map_copy)
				local Monster21 = CreateChaEx(860, 12975, 10800, 145, 180, map_copy)
				local Monster22 = CreateChaEx(860, 11975, 13225, 145, 180, map_copy)
				SetChaLifeTime(Monster16, 299050)
				SetChaLifeTime(Monster17, 299100)
				SetChaLifeTime(Monster18, 299150)
				SetChaLifeTime(Monster19, 299200)
				SetChaLifeTime(Monster20, 299250)
				SetChaLifeTime(Monster21, 299300)
				SetChaLifeTime(Monster22, 299350)
				--GMNotice(Message)
				dreampk_Wave2 = dreampk_Wave2 + 1
			end
		end
		if Minute == 15 and Second == 0 then
		GMNotice(Message)
			if dreampk_Wave3 == 0 then
				local Monster23 = CreateChaEx(861, 9625, 9500, 145, 180, map_copy)
				local Monster24 = CreateChaEx(861, 14575, 9325, 145, 180, map_copy)
				local Monster25 = CreateChaEx(861, 14125, 14175, 145, 180, map_copy)
				local Monster26 = CreateChaEx(861, 10100, 13950, 145, 180, map_copy)
				local Monster27 = CreateChaEx(861, 12025, 8375, 145, 180, map_copy)
				local Monster28 = CreateChaEx(861, 11975, 15075, 145, 180, map_copy)
				local Monster29 = CreateChaEx(861, 12000, 11125, 145, 180, map_copy)
				SetChaLifeTime(Monster23, 299050)
				SetChaLifeTime(Monster24, 299100)
				SetChaLifeTime(Monster25, 299150)
				SetChaLifeTime(Monster26, 299200)
				SetChaLifeTime(Monster27, 299250)
				SetChaLifeTime(Monster28, 299300)
				SetChaLifeTime(Monster29, 299350)
				--GMNotice(Message)
				dreampk_Wave3 = dreampk_Wave3 + 1
			end
		end
		if Minute == 20 and Second == 0 then
		GMNotice(Message)
			if dreampk_Wave4 == 0 then
				local Monster30 = CreateChaEx(875, 6575, 6075, 145, 60, map_copy)
				local Monster31 = CreateChaEx(872, 9125, 9300, 145, 60, map_copy)
				local Monster32 = CreateChaEx(868, 11325, 11425, 145, 60, map_copy)
				local Monster33 = CreateChaEx(872, 12725, 12950, 145, 60, map_copy)
				local Monster34 = CreateChaEx(879, 14875, 15050, 145, 60, map_copy)
				local Monster35 = CreateChaEx(872, 16750, 17125, 145, 60, map_copy)
				local Monster36 = CreateChaEx(875, 15950, 17175, 145, 60, map_copy)
				local Monster37 = CreateChaEx(868, 12200, 18225, 145, 60, map_copy)
				local Monster38 = CreateChaEx(868, 9650, 17975, 145, 60, map_copy)
				local Monster39 = CreateChaEx(868, 6950, 18050, 145, 60, map_copy)
				local Monster40 = CreateChaEx(879, 6500, 14475, 145, 60, map_copy)
				local Monster41 = CreateChaEx(879, 6525, 11900, 145, 60, map_copy)
				local Monster42 = CreateChaEx(875, 9300, 12050, 145, 60, map_copy)
				local Monster43 = CreateChaEx(875, 10950, 11975, 145, 60, map_copy)
				local Monster44 = CreateChaEx(872, 13450, 11925, 145, 60, map_copy)
				local Monster45 = CreateChaEx(879, 15600, 12000, 145, 60, map_copy)
				local Monster46 = CreateChaEx(875, 17525, 12125, 145, 60, map_copy)
				local Monster47 = CreateChaEx(875, 17600, 6175, 145, 60, map_copy)
				local Monster48 = CreateChaEx(868, 15975, 7925, 145, 60, map_copy)
				local Monster49 = CreateChaEx(868, 14400, 9575, 145, 60, map_copy)
				local Monster50 = CreateChaEx(868, 12025, 5875, 145, 60, map_copy)
				local Monster51 = CreateChaEx(868, 12000, 7300, 145, 60, map_copy)
				SetChaLifeTime(Monster30, 298050)
				SetChaLifeTime(Monster31, 298100)
				SetChaLifeTime(Monster32, 298150)
				SetChaLifeTime(Monster33, 298200)
				SetChaLifeTime(Monster34, 298250)
				SetChaLifeTime(Monster35, 298300)
				SetChaLifeTime(Monster36, 298350)
				SetChaLifeTime(Monster37, 298400)
				SetChaLifeTime(Monster38, 298450)
				SetChaLifeTime(Monster39, 298500)
				SetChaLifeTime(Monster40, 298550)
				SetChaLifeTime(Monster41, 298600)
				SetChaLifeTime(Monster42, 298650)
				SetChaLifeTime(Monster43, 298700)
				SetChaLifeTime(Monster44, 298750)
				SetChaLifeTime(Monster45, 298800)
				SetChaLifeTime(Monster46, 298850)
				SetChaLifeTime(Monster47, 298900)
				SetChaLifeTime(Monster48, 298950)
				SetChaLifeTime(Monster49, 299000)
				SetChaLifeTime(Monster50, 299050)
				SetChaLifeTime(Monster51, 299100)
				--GMNotice(Message)
				dreampk_Wave4 = dreampk_Wave4 + 1
			end
		end
		if Minute == 25 and Second == 0 then
		GMNotice(Message)
			if dreampk_Wave5 == 0 then
				local Monster52 = CreateChaEx(869, 6575, 6075, 145, 60, map_copy)
				local Monster53 = CreateChaEx(880, 9125, 9300, 145, 60, map_copy)
				local Monster54 = CreateChaEx(876, 11325, 11425, 145, 60, map_copy)
				local Monster55 = CreateChaEx(876, 12725, 12950, 145, 60, map_copy)
				local Monster56 = CreateChaEx(869, 14875, 15050, 145, 60, map_copy)
				local Monster57 = CreateChaEx(869, 16750, 17125, 145, 60, map_copy)
				local Monster58 = CreateChaEx(880, 15950, 17175, 145, 60, map_copy)
				local Monster59 = CreateChaEx(880, 12200, 18225, 145, 60, map_copy)
				local Monster60 = CreateChaEx(876, 9650, 17975, 145, 60, map_copy)
				local Monster61 = CreateChaEx(869, 6950, 18050, 145, 60, map_copy)
				local Monster62 = CreateChaEx(869, 6500, 14475, 145, 60, map_copy)
				local Monster63 = CreateChaEx(873, 6525, 11900, 145, 60, map_copy)
				local Monster64 = CreateChaEx(869, 9300, 12050, 145, 60, map_copy)
				local Monster65 = CreateChaEx(880, 10950, 11975, 145, 60, map_copy)
				local Monster66 = CreateChaEx(876, 13450, 11925, 145, 60, map_copy)
				local Monster67 = CreateChaEx(873, 15600, 12000, 145, 60, map_copy)
				local Monster68 = CreateChaEx(880, 17525, 12125, 145, 60, map_copy)
				local Monster69 = CreateChaEx(873, 17600, 6175, 145, 60, map_copy)
				local Monster70 = CreateChaEx(869, 15975, 7925, 145, 60, map_copy)
				local Monster71 = CreateChaEx(873, 14400, 9575, 145, 60, map_copy)
				local Monster72 = CreateChaEx(880, 12025, 5875, 145, 60, map_copy)
				local Monster73 = CreateChaEx(869, 12000, 7300, 145, 60, map_copy)
				local Monster74 = CreateChaEx(873, 7250, 5925, 145, 60, map_copy)
				local Monster75 = CreateChaEx(869, 9350, 6025, 145, 60, map_copy)
				local Monster76 = CreateChaEx(873, 11075, 5825, 145, 60, map_copy)
				local Monster77 = CreateChaEx(880, 13875, 6025, 145, 60, map_copy)
				local Monster78 = CreateChaEx(876, 15925, 6050, 145, 60, map_copy)
				local Monster79 = CreateChaEx(873, 18275, 5625, 145, 60, map_copy)
				local Monster80 = CreateChaEx(869, 17775, 7325, 145, 60, map_copy)
				local Monster81 = CreateChaEx(876, 17725, 9025, 145, 60, map_copy)
				local Monster82 = CreateChaEx(873, 17650, 10850, 145, 60, map_copy)
				local Monster83 = CreateChaEx(869, 17800, 12150, 145, 60, map_copy)
				local Monster84 = CreateChaEx(879, 17400, 14425, 145, 60, map_copy)
				local Monster85 = CreateChaEx(876, 17750, 16800, 145, 60, map_copy)
				local Monster86 = CreateChaEx(880, 16100, 18150, 145, 60, map_copy)
				local Monster87 = CreateChaEx(873, 14475, 18100, 145, 60, map_copy)
				local Monster88 = CreateChaEx(869, 10125, 18175, 145, 60, map_copy)
				local Monster89 = CreateChaEx(873, 7825, 18125, 145, 60, map_copy)
				local Monster90 = CreateChaEx(880, 6375, 16725, 145, 60, map_copy)
				local Monster91 = CreateChaEx(876, 7475, 14225, 145, 60, map_copy)
				local Monster92 = CreateChaEx(873, 4575, 11925, 145, 60, map_copy)
				local Monster93 = CreateChaEx(876, 7500, 9625, 145, 60, map_copy)
				SetChaLifeTime(Monster52, 297050)
				SetChaLifeTime(Monster53, 297100)
				SetChaLifeTime(Monster54, 297150)
				SetChaLifeTime(Monster55, 297200)
				SetChaLifeTime(Monster56, 297250)
				SetChaLifeTime(Monster57, 297300)
				SetChaLifeTime(Monster58, 297350)
				SetChaLifeTime(Monster59, 297400)
				SetChaLifeTime(Monster60, 297450)
				SetChaLifeTime(Monster61, 297500)
				SetChaLifeTime(Monster62, 297550)
				SetChaLifeTime(Monster63, 297600)
				SetChaLifeTime(Monster64, 297650)
				SetChaLifeTime(Monster65, 297700)
				SetChaLifeTime(Monster66, 297750)
				SetChaLifeTime(Monster67, 297800)
				SetChaLifeTime(Monster68, 297850)
				SetChaLifeTime(Monster69, 297900)
				SetChaLifeTime(Monster70, 297950)
				SetChaLifeTime(Monster71, 298000)
				SetChaLifeTime(Monster72, 298050)
				SetChaLifeTime(Monster73, 298100)
				SetChaLifeTime(Monster74, 298150)
				SetChaLifeTime(Monster75, 298200)
				SetChaLifeTime(Monster76, 298250)
				SetChaLifeTime(Monster77, 298300)
				SetChaLifeTime(Monster78, 298350)
				SetChaLifeTime(Monster79, 298400)
				SetChaLifeTime(Monster80, 298450)
				SetChaLifeTime(Monster81, 298500)
				SetChaLifeTime(Monster82, 298550)
				SetChaLifeTime(Monster83, 298600)
				SetChaLifeTime(Monster84, 298650)
				SetChaLifeTime(Monster85, 298700)
				SetChaLifeTime(Monster86, 298750)
				SetChaLifeTime(Monster87, 298800)
				SetChaLifeTime(Monster88, 298850)
				SetChaLifeTime(Monster89, 298900)
				SetChaLifeTime(Monster90, 298950)
				SetChaLifeTime(Monster91, 299000)
				SetChaLifeTime(Monster92, 299050)
				SetChaLifeTime(Monster93, 299100)
				--GMNotice(Message)
				dreampk_Wave5 = dreampk_Wave5 + 1
			end
		end
		if Minute == 30 and Second == 0 then
		GMNotice(Message)
			if dreampk_Wave6 == 0 then
				local Monster94 = CreateChaEx(883, 9125, 9300, 145, 60, map_copy)
				local Monster95 = CreateChaEx(886, 11325, 11425, 145, 60, map_copy)
				local Monster96 = CreateChaEx(884, 12725, 12950, 145, 60, map_copy)
				local Monster97 = CreateChaEx(884, 14875, 15050, 145, 60, map_copy)
				local Monster98 = CreateChaEx(883, 16750, 17125, 145, 60, map_copy)
				local Monster99 = CreateChaEx(883, 15950, 17175, 145, 60, map_copy)
				local Monster100 = CreateChaEx(886, 12200, 18225, 145, 60, map_copy)
				local Monster101 = CreateChaEx(886, 9650, 17975, 145, 60, map_copy)
				local Monster102 = CreateChaEx(884, 6500, 14475, 145, 60, map_copy)
				local Monster103 = CreateChaEx(883, 6525, 11900, 145, 60, map_copy)
				local Monster104 = CreateChaEx(883, 9300, 12050, 145, 60, map_copy)
				local Monster105 = CreateChaEx(885, 10950, 11975, 145, 60, map_copy)
				local Monster106 = CreateChaEx(883, 13450, 11925, 145, 60, map_copy)
				local Monster107 = CreateChaEx(886, 15600, 12000, 145, 60, map_copy)
				local Monster108 = CreateChaEx(884, 17525, 12125, 145, 60, map_copy)
				local Monster109 = CreateChaEx(885, 17600, 6175, 145, 60, map_copy)
				local Monster110 = CreateChaEx(886, 15975, 7925, 145, 60, map_copy)
				local Monster111 = CreateChaEx(885, 14400, 9575, 145, 60, map_copy)
				local Monster112 = CreateChaEx(883, 12025, 5875, 145, 60, map_copy)
				local Monster113 = CreateChaEx(885, 12000, 7300, 145, 60, map_copy)
				local Monster114 = CreateChaEx(886, 7250, 5925, 145, 60, map_copy)
				local Monster115 = CreateChaEx(883, 9350, 6025, 145, 60, map_copy)
				local Monster116 = CreateChaEx(885, 11075, 5825, 145, 60, map_copy)
				local Monster117 = CreateChaEx(883, 13875, 6025, 145, 60, map_copy)
				local Monster118 = CreateChaEx(885, 15925, 6050, 145, 60, map_copy)
				local Monster119 = CreateChaEx(886, 18275, 5625, 145, 60, map_copy)
				local Monster120 = CreateChaEx(884, 17775, 7325, 145, 60, map_copy)
				local Monster121 = CreateChaEx(885, 17725, 9025, 145, 60, map_copy)
				local Monster122 = CreateChaEx(883, 17650, 10850, 145, 60, map_copy)
				local Monster123 = CreateChaEx(884, 17800, 12150, 145, 60, map_copy)
				local Monster124 = CreateChaEx(885, 17400, 14425, 145, 60, map_copy)
				local Monster125 = CreateChaEx(883, 17750, 16800, 145, 60, map_copy)
				local Monster126 = CreateChaEx(886, 16100, 18150, 145, 60, map_copy)
				local Monster127 = CreateChaEx(884, 14475, 18100, 145, 60, map_copy)
				local Monster128 = CreateChaEx(886, 10125, 18175, 145, 60, map_copy)
				local Monster129 = CreateChaEx(885, 7825, 18125, 145, 60, map_copy)
				local Monster130 = CreateChaEx(883, 6375, 16725, 145, 60, map_copy)
				local Monster131 = CreateChaEx(885, 7475, 14225, 145, 60, map_copy)
				local Monster132 = CreateChaEx(886, 4575, 11925, 145, 60, map_copy)
				local Monster133 = CreateChaEx(884, 7500, 9625, 145, 60, map_copy)
				local Monster134 = CreateChaEx(885, 4500, 4250, 145, 60, map_copy)
				local Monster135 = CreateChaEx(884, 4525, 6500, 145, 60, map_copy)
				local Monster136 = CreateChaEx(884, 4500, 7975, 145, 60, map_copy)
				local Monster137 = CreateChaEx(885, 4550, 9725, 145, 60, map_copy)
				local Monster138 = CreateChaEx(886, 4275, 11375, 145, 60, map_copy)
				local Monster139 = CreateChaEx(883, 4275, 13475, 145, 60, map_copy)
				local Monster140 = CreateChaEx(884, 4475, 15400, 145, 60, map_copy)
				local Monster141 = CreateChaEx(884, 4325, 18500, 145, 60, map_copy)
				local Monster142 = CreateChaEx(885, 5175, 19925, 145, 60, map_copy)
				local Monster143 = CreateChaEx(886, 7700, 20075, 145, 60, map_copy)
				local Monster144 = CreateChaEx(886, 9700, 19900, 145, 60, map_copy)
				local Monster145 = CreateChaEx(886, 11775, 19825, 145, 60, map_copy)
				local Monster146 = CreateChaEx(885, 14500, 19975, 145, 60, map_copy)
				local Monster147 = CreateChaEx(886, 16750, 19825, 145, 60, map_copy)
				local Monster148 = CreateChaEx(885, 19000, 19850, 145, 60, map_copy)
				local Monster149 = CreateChaEx(877, 19575, 17100, 145, 60, map_copy)
				local Monster150 = CreateChaEx(886, 19475, 14675, 145, 60, map_copy)
				local Monster151 = CreateChaEx(886, 19525, 12725, 145, 60, map_copy)
				local Monster153 = CreateChaEx(886, 19650, 9975, 145, 60, map_copy)
				local Monster154 = CreateChaEx(885, 19475, 7475, 145, 60, map_copy)
				local Monster155 = CreateChaEx(884, 19225, 4600, 145, 60, map_copy)
				local Monster156 = CreateChaEx(886, 18025, 4075, 145, 60, map_copy)
				local Monster157 = CreateChaEx(885, 16450, 4075, 145, 60, map_copy)
				local Monster158 = CreateChaEx(886, 14350, 4050, 145, 60, map_copy)
				local Monster159 = CreateChaEx(884, 12125, 4125, 145, 60, map_copy)
				local Monster160 = CreateChaEx(883, 9475, 4050, 145, 60, map_copy)
				local Monster161 = CreateChaEx(884, 6500, 3875, 145, 60, map_copy)
				local Monster162 = CreateChaEx(886, 4875, 4025, 145, 60, map_copy)
				local Monster163 = CreateChaEx(886, 7275, 9650, 145, 60, map_copy)
				local Monster164 = CreateChaEx(885, 16275, 9800, 145, 60, map_copy)
				local Monster165 = CreateChaEx(886, 16325, 14425, 145, 60, map_copy)
				local Monster166 = CreateChaEx(885, 7800, 14075, 145, 60, map_copy)
				local Monster167 = CreateChaEx(883, 11050, 12750, 145, 60, map_copy)
				SetChaLifeTime(Monster94, 296050)
				SetChaLifeTime(Monster95, 296100)
				SetChaLifeTime(Monster96, 296150)
				SetChaLifeTime(Monster97, 296200)
				SetChaLifeTime(Monster98, 296250)
				SetChaLifeTime(Monster99, 296300)
				SetChaLifeTime(Monster100, 296350)
				SetChaLifeTime(Monster101, 296400)
				SetChaLifeTime(Monster102, 296450)
				SetChaLifeTime(Monster103, 296500)
				SetChaLifeTime(Monster104, 296550)
				SetChaLifeTime(Monster105, 296600)
				SetChaLifeTime(Monster106, 296650)
				SetChaLifeTime(Monster107, 296700)
				SetChaLifeTime(Monster108, 296750)
				SetChaLifeTime(Monster109, 296800)
				SetChaLifeTime(Monster110, 296850)
				SetChaLifeTime(Monster111, 296900)
				SetChaLifeTime(Monster112, 296950)
				SetChaLifeTime(Monster113, 297000)
				SetChaLifeTime(Monster114, 297050)
				SetChaLifeTime(Monster115, 297100)
				SetChaLifeTime(Monster116, 297150)
				SetChaLifeTime(Monster117, 297200)
				SetChaLifeTime(Monster118, 297250)
				SetChaLifeTime(Monster119, 297300)
				SetChaLifeTime(Monster120, 297350)
				SetChaLifeTime(Monster121, 297400)
				SetChaLifeTime(Monster122, 297450)
				SetChaLifeTime(Monster123, 297500)
				SetChaLifeTime(Monster124, 297550)
				SetChaLifeTime(Monster125, 297600)
				SetChaLifeTime(Monster126, 297650)
				SetChaLifeTime(Monster127, 297700)
				SetChaLifeTime(Monster128, 297750)
				SetChaLifeTime(Monster129, 297800)
				SetChaLifeTime(Monster130, 297850)
				SetChaLifeTime(Monster131, 297900)
				SetChaLifeTime(Monster132, 297950)
				SetChaLifeTime(Monster133, 298000)
				SetChaLifeTime(Monster134, 298050)
				SetChaLifeTime(Monster135, 298100)
				SetChaLifeTime(Monster136, 298150)
				SetChaLifeTime(Monster137, 298200)
				SetChaLifeTime(Monster138, 298250)
				SetChaLifeTime(Monster139, 298300)
				SetChaLifeTime(Monster140, 298350)
				SetChaLifeTime(Monster141, 298400)
				SetChaLifeTime(Monster142, 298450)
				SetChaLifeTime(Monster143, 298500)
				SetChaLifeTime(Monster144, 298550)
				SetChaLifeTime(Monster145, 298600)
				SetChaLifeTime(Monster146, 298650)
				SetChaLifeTime(Monster147, 298700)
				SetChaLifeTime(Monster148, 298750)
				SetChaLifeTime(Monster149, 298800)
				SetChaLifeTime(Monster150, 298850)
				SetChaLifeTime(Monster151, 298900)
				SetChaLifeTime(Monster152, 298950)
				SetChaLifeTime(Monster153, 299000)
				SetChaLifeTime(Monster154, 299050)
				SetChaLifeTime(Monster155, 299100)
				SetChaLifeTime(Monster156, 299150)
				SetChaLifeTime(Monster157, 299200)
				SetChaLifeTime(Monster158, 299250)
				SetChaLifeTime(Monster159, 299300)
				SetChaLifeTime(Monster160, 299350)
				SetChaLifeTime(Monster161, 299400)
				SetChaLifeTime(Monster162, 299450)
				SetChaLifeTime(Monster163, 299500)
				SetChaLifeTime(Monster164, 299550)
				SetChaLifeTime(Monster165, 299600)
				SetChaLifeTime(Monster166, 299650)
				SetChaLifeTime(Monster167, 299700)
				--GMNotice(Message)
				dreampk_Wave6 = dreampk_Wave6 + 1
			end
		end
		if Minute == 35 and Second == 0 then
		GMNotice(Message)
			if dreampk_Wave7 == 0 then
				local Monster168 = CreateChaEx(883, 9125, 9300, 145, 60, map_copy)
				local Monster169 = CreateChaEx(886, 11325, 11425, 145, 60, map_copy)
				local Monster170 = CreateChaEx(884, 12725, 12950, 145, 60, map_copy)
				local Monster171 = CreateChaEx(884, 14875, 15050, 145, 60, map_copy)
				local Monster172 = CreateChaEx(883, 16750, 17125, 145, 60, map_copy)
				local Monster173 = CreateChaEx(883, 15950, 17175, 145, 60, map_copy)
				local Monster174 = CreateChaEx(886, 12200, 18225, 145, 60, map_copy)
				local Monster175 = CreateChaEx(886, 9650, 17975, 145, 60, map_copy)
				local Monster176 = CreateChaEx(884, 6500, 14475, 145, 60, map_copy)
				local Monster177 = CreateChaEx(883, 6525, 11900, 145, 60, map_copy)
				local Monster178 = CreateChaEx(883, 9300, 12050, 145, 60, map_copy)
				local Monster179 = CreateChaEx(885, 10950, 11975, 145, 60, map_copy)
				local Monster180 = CreateChaEx(883, 13450, 11925, 145, 60, map_copy)
				local Monster181 = CreateChaEx(886, 15600, 12000, 145, 60, map_copy)
				local Monster182 = CreateChaEx(884, 17525, 12125, 145, 60, map_copy)
				local Monster183 = CreateChaEx(885, 17600, 6175, 145, 60, map_copy)
				local Monster184 = CreateChaEx(886, 15975, 7925, 145, 60, map_copy)
				local Monster185 = CreateChaEx(885, 14400, 9575, 145, 60, map_copy)
				local Monster186 = CreateChaEx(883, 12025, 5875, 145, 60, map_copy)
				local Monster187 = CreateChaEx(885, 12000, 7300, 145, 60, map_copy)
				local Monster188 = CreateChaEx(886, 7250, 5925, 145, 60, map_copy)
				local Monster189 = CreateChaEx(883, 9350, 6025, 145, 60, map_copy)
				local Monster190 = CreateChaEx(885, 11075, 5825, 145, 60, map_copy)
				local Monster191 = CreateChaEx(883, 13875, 6025, 145, 60, map_copy)
				local Monster192 = CreateChaEx(885, 15925, 6050, 145, 60, map_copy)
				local Monster193 = CreateChaEx(886, 18275, 5625, 145, 60, map_copy)
				local Monster194 = CreateChaEx(884, 17775, 7325, 145, 60, map_copy)
				local Monster195 = CreateChaEx(885, 17725, 9025, 145, 60, map_copy)
				local Monster196 = CreateChaEx(883, 17650, 10850, 145, 60, map_copy)
				local Monster197 = CreateChaEx(884, 17800, 12150, 145, 60, map_copy)
				local Monster198 = CreateChaEx(885, 17400, 14425, 145, 60, map_copy)
				local Monster199 = CreateChaEx(883, 17750, 16800, 145, 60, map_copy)
				local Monster200 = CreateChaEx(886, 16100, 18150, 145, 60, map_copy)
				local Monster201 = CreateChaEx(884, 14475, 18100, 145, 60, map_copy)
				local Monster202 = CreateChaEx(886, 10125, 18175, 145, 60, map_copy)
				local Monster203 = CreateChaEx(885, 7825, 18125, 145, 60, map_copy)
				local Monster204 = CreateChaEx(883, 6375, 16725, 145, 60, map_copy)
				local Monster205 = CreateChaEx(885, 7475, 14225, 145, 60, map_copy)
				local Monster206 = CreateChaEx(886, 4575, 11925, 145, 60, map_copy)
				local Monster207 = CreateChaEx(884, 7500, 9625, 145, 60, map_copy)
				local Monster208 = CreateChaEx(885, 4500, 4250, 145, 60, map_copy)
				local Monster209 = CreateChaEx(884, 4525, 6500, 145, 60, map_copy)
				local Monster210 = CreateChaEx(884, 4500, 7975, 145, 60, map_copy)
				local Monster211 = CreateChaEx(885, 4550, 9725, 145, 60, map_copy)
				local Monster212 = CreateChaEx(886, 4275, 11375, 145, 60, map_copy)
				local Monster213 = CreateChaEx(883, 4275, 13475, 145, 60, map_copy)
				local Monster214 = CreateChaEx(884, 4475, 15400, 145, 60, map_copy)
				local Monster215 = CreateChaEx(884, 4325, 18500, 145, 60, map_copy)
				local Monster216 = CreateChaEx(885, 5175, 19925, 145, 60, map_copy)
				local Monster217 = CreateChaEx(886, 7700, 20075, 145, 60, map_copy)
				local Monster218 = CreateChaEx(886, 9700, 19900, 145, 60, map_copy)
				local Monster219 = CreateChaEx(886, 11775, 19825, 145, 60, map_copy)
				local Monster220 = CreateChaEx(885, 14500, 19975, 145, 60, map_copy)
				local Monster221 = CreateChaEx(886, 16750, 19825, 145, 60, map_copy)
				local Monster222 = CreateChaEx(885, 19000, 19850, 145, 60, map_copy)
				local Monster223 = CreateChaEx(877, 19575, 17100, 145, 60, map_copy)
				local Monster224 = CreateChaEx(886, 19475, 14675, 145, 60, map_copy)
				local Monster225 = CreateChaEx(886, 19525, 12725, 145, 60, map_copy)
				local Monster226 = CreateChaEx(886, 19650, 9975, 145, 60, map_copy)
				local Monster227 = CreateChaEx(885, 19475, 7475, 145, 60, map_copy)
				local Monster228 = CreateChaEx(884, 19225, 4600, 145, 60, map_copy)
				local Monster229 = CreateChaEx(886, 18025, 4075, 145, 60, map_copy)
				local Monster230 = CreateChaEx(885, 16450, 4075, 145, 60, map_copy)
				local Monster231 = CreateChaEx(886, 14350, 4050, 145, 60, map_copy)
				local Monster232 = CreateChaEx(884, 12125, 4125, 145, 60, map_copy)
				local Monster233 = CreateChaEx(883, 9475, 4050, 145, 60, map_copy)
				local Monster234 = CreateChaEx(884, 6500, 3875, 145, 60, map_copy)
				local Monster235 = CreateChaEx(886, 4875, 4025, 145, 60, map_copy)
				local Monster236 = CreateChaEx(886, 7275, 9650, 145, 60, map_copy)
				local Monster237 = CreateChaEx(885, 16275, 9800, 145, 60, map_copy)
				local Monster238 = CreateChaEx(886, 16325, 14425, 145, 60, map_copy)
				local Monster239 = CreateChaEx(885, 7800, 14075, 145, 60, map_copy)
				local Monster240 = CreateChaEx(883, 11050, 12750, 145, 60, map_copy)
				local Monster241 = CreateChaEx(884, 4325, 18500, 145, 60, map_copy)
				local Monster242 = CreateChaEx(885, 5175, 19925, 145, 60, map_copy)
				local Monster243 = CreateChaEx(886, 7700, 20075, 145, 60, map_copy)
				local Monster244 = CreateChaEx(886, 9700, 19900, 145, 60, map_copy)
				local Monster245 = CreateChaEx(886, 11775, 19825, 145, 60, map_copy)
				local Monster246 = CreateChaEx(885, 14500, 19975, 145, 60, map_copy)
				local Monster247 = CreateChaEx(886, 16750, 19825, 145, 60, map_copy)
				local Monster248 = CreateChaEx(885, 19000, 19850, 145, 60, map_copy)
				local Monster249 = CreateChaEx(877, 19575, 17100, 145, 60, map_copy)
				local Monster250 = CreateChaEx(886, 19475, 14675, 145, 60, map_copy)
				local Monster251 = CreateChaEx(886, 19525, 12725, 145, 60, map_copy)
				local Monster252 = CreateChaEx(886, 19650, 9975, 145, 60, map_copy)
				local Monster253 = CreateChaEx(885, 19475, 7475, 145, 60, map_copy)
				local Monster254 = CreateChaEx(884, 19225, 4600, 145, 60, map_copy)
				local Monster255 = CreateChaEx(886, 18025, 4075, 145, 60, map_copy)
				local Monster256 = CreateChaEx(885, 16450, 4075, 145, 60, map_copy)
				local Monster257 = CreateChaEx(886, 14350, 4050, 145, 60, map_copy)
				local Monster258 = CreateChaEx(884, 12125, 4125, 145, 60, map_copy)
				local Monster259 = CreateChaEx(883, 9475, 4050, 145, 60, map_copy)
				local Monster260 = CreateChaEx(884, 6500, 3875, 145, 60, map_copy)
				local Monster261 = CreateChaEx(886, 4875, 4025, 145, 60, map_copy)
				local Monster262 = CreateChaEx(886, 7275, 9650, 145, 60, map_copy)
				local Monster263 = CreateChaEx(885, 16275, 9800, 145, 60, map_copy)
				local Monster264 = CreateChaEx(886, 16325, 14425, 145, 60, map_copy)
				local Monster265 = CreateChaEx(885, 7800, 14075, 145, 60, map_copy)
				local Monster266 = CreateChaEx(883, 11050, 12750, 145, 60, map_copy)
				local Monster267 = CreateChaEx(883, 9125, 9300, 145, 60, map_copy)
				local Monster268 = CreateChaEx(886, 11325, 11425, 145, 60, map_copy)
				local Monster269 = CreateChaEx(884, 12725, 12950, 145, 60, map_copy)
				local Monster270 = CreateChaEx(884, 14875, 15050, 145, 60, map_copy)
				local Monster271 = CreateChaEx(883, 16750, 17125, 145, 60, map_copy)
				local Monster272 = CreateChaEx(883, 15950, 17175, 145, 60, map_copy)
				local Monster273 = CreateChaEx(886, 12200, 18225, 145, 60, map_copy)
				local Monster274 = CreateChaEx(886, 9650, 17975, 145, 60, map_copy)
				local Monster275 = CreateChaEx(884, 6500, 14475, 145, 60, map_copy)
				local Monster276 = CreateChaEx(883, 6525, 11900, 145, 60, map_copy)
				local Monster277 = CreateChaEx(883, 9300, 12050, 145, 60, map_copy)
				local Monster278 = CreateChaEx(885, 10950, 11975, 145, 60, map_copy)
				local Monster289 = CreateChaEx(883, 13450, 11925, 145, 60, map_copy)
				local Monster290 = CreateChaEx(886, 15600, 12000, 145, 60, map_copy)
				local Monster291 = CreateChaEx(884, 17525, 12125, 145, 60, map_copy)
				local Monster292 = CreateChaEx(885, 17600, 6175, 145, 60, map_copy)
				local Monster293 = CreateChaEx(886, 15975, 7925, 145, 60, map_copy)
				local Monster294 = CreateChaEx(885, 14400, 9575, 145, 60, map_copy)
				local Monster295 = CreateChaEx(883, 12025, 5875, 145, 60, map_copy)
				local Monster296 = CreateChaEx(885, 12000, 7300, 145, 60, map_copy)
				local Monster297 = CreateChaEx(886, 7250, 5925, 145, 60, map_copy)
				local Monster298 = CreateChaEx(883, 9350, 6025, 145, 60, map_copy)
				local Monster299 = CreateChaEx(885, 11075, 5825, 145, 60, map_copy)
				local Monster300 = CreateChaEx(883, 13875, 6025, 145, 60, map_copy)
				local Monster301 = CreateChaEx(885, 15925, 6050, 145, 60, map_copy)
				local Monster302 = CreateChaEx(886, 18275, 5625, 145, 60, map_copy)
				local Monster303 = CreateChaEx(884, 17775, 7325, 145, 60, map_copy)
				local Monster304 = CreateChaEx(885, 17725, 9025, 145, 60, map_copy)
				local Monster305 = CreateChaEx(883, 17650, 10850, 145, 60, map_copy)
				local Monster306 = CreateChaEx(884, 17800, 12150, 145, 60, map_copy)
				local Monster307 = CreateChaEx(885, 17400, 14425, 145, 60, map_copy)
				local Monster308 = CreateChaEx(883, 17750, 16800, 145, 60, map_copy)
				local Monster309 = CreateChaEx(886, 16100, 18150, 145, 60, map_copy)
				local Monster310 = CreateChaEx(884, 14475, 18100, 145, 60, map_copy)
				local Monster311 = CreateChaEx(886, 10125, 18175, 145, 60, map_copy)
				local Monster312 = CreateChaEx(885, 7825, 18125, 145, 60, map_copy)
				local Monster313 = CreateChaEx(883, 6375, 16725, 145, 60, map_copy)
				local Monster314 = CreateChaEx(885, 7475, 14225, 145, 60, map_copy)
				local Monster315 = CreateChaEx(886, 4575, 11925, 145, 60, map_copy)
				local Monster316 = CreateChaEx(884, 7500, 9625, 145, 60, map_copy)
				local Monster317 = CreateChaEx(885, 4500, 4250, 145, 60, map_copy)
				local Monster318 = CreateChaEx(884, 4525, 6500, 145, 60, map_copy)
				local Monster319 = CreateChaEx(884, 4500, 7975, 145, 60, map_copy)
				local Monster320 = CreateChaEx(885, 4550, 9725, 145, 60, map_copy)
				local Monster321 = CreateChaEx(886, 4275, 11375, 145, 60, map_copy)
				local Monster322 = CreateChaEx(883, 4275, 13475, 145, 60, map_copy)
				local Monster323 = CreateChaEx(884, 4475, 15400, 145, 60, map_copy)
				local Monster324 = CreateChaEx(884, 4325, 18500, 145, 60, map_copy)
				local Monster325 = CreateChaEx(883, 9350, 6025, 145, 60, map_copy)
				local Monster326 = CreateChaEx(885, 11075, 5825, 145, 60, map_copy)
				local Monster327 = CreateChaEx(883, 13875, 6025, 145, 60, map_copy)
				local Monster328 = CreateChaEx(885, 15925, 6050, 145, 60, map_copy)
				local Monster329 = CreateChaEx(886, 18275, 5625, 145, 60, map_copy)
				local Monster330 = CreateChaEx(884, 17775, 7325, 145, 60, map_copy)
				local Monster331 = CreateChaEx(885, 17725, 9025, 145, 60, map_copy)
				local Monster332 = CreateChaEx(883, 17650, 10850, 145, 60, map_copy)
				local Monster333 = CreateChaEx(884, 17800, 12150, 145, 60, map_copy)
				local Monster334 = CreateChaEx(885, 17400, 14425, 145, 60, map_copy)
				local Monster335 = CreateChaEx(1840, 10162, 11875, 145, 60, map_copy)
				SetChaLifeTime(Monster168, 290050)
				SetChaLifeTime(Monster169, 290100)
				SetChaLifeTime(Monster170, 290150)
				SetChaLifeTime(Monster171, 290200)
				SetChaLifeTime(Monster172, 290250)
				SetChaLifeTime(Monster173, 290300)
				SetChaLifeTime(Monster174, 290350)
				SetChaLifeTime(Monster175, 290400)
				SetChaLifeTime(Monster176, 290450)
				SetChaLifeTime(Monster177, 290500)
				SetChaLifeTime(Monster178, 290550)
				SetChaLifeTime(Monster179, 290600)
				SetChaLifeTime(Monster180, 290650)
				SetChaLifeTime(Monster181, 290700)
				SetChaLifeTime(Monster182, 290750)
				SetChaLifeTime(Monster183, 290800)
				SetChaLifeTime(Monster184, 290850)
				SetChaLifeTime(Monster185, 290900)
				SetChaLifeTime(Monster186, 290950)
				SetChaLifeTime(Monster187, 291000)
				SetChaLifeTime(Monster188, 291050)
				SetChaLifeTime(Monster189, 291100)
				SetChaLifeTime(Monster190, 291150)
				SetChaLifeTime(Monster191, 291200)
				SetChaLifeTime(Monster192, 291250)
				SetChaLifeTime(Monster193, 291300)
				SetChaLifeTime(Monster194, 291350)
				SetChaLifeTime(Monster195, 291400)
				SetChaLifeTime(Monster196, 291450)
				SetChaLifeTime(Monster197, 291500)
				SetChaLifeTime(Monster198, 291550)
				SetChaLifeTime(Monster199, 291600)
				SetChaLifeTime(Monster200, 291650)
				SetChaLifeTime(Monster201, 291700)
				SetChaLifeTime(Monster202, 291750)
				SetChaLifeTime(Monster203, 291800)
				SetChaLifeTime(Monster204, 291850)
				SetChaLifeTime(Monster205, 291900)
				SetChaLifeTime(Monster206, 291950)
				SetChaLifeTime(Monster207, 292000)
				SetChaLifeTime(Monster208, 292050)
				SetChaLifeTime(Monster209, 292100)
				SetChaLifeTime(Monster210, 292150)
				SetChaLifeTime(Monster211, 292200)
				SetChaLifeTime(Monster212, 292250)
				SetChaLifeTime(Monster213, 292300)
				SetChaLifeTime(Monster214, 292350)
				SetChaLifeTime(Monster215, 292400)
				SetChaLifeTime(Monster216, 292450)
				SetChaLifeTime(Monster217, 292500)
				SetChaLifeTime(Monster218, 292550)
				SetChaLifeTime(Monster219, 292600)
				SetChaLifeTime(Monster220, 292650)
				SetChaLifeTime(Monster221, 292700)
				SetChaLifeTime(Monster222, 292750)
				SetChaLifeTime(Monster223, 292800)
				SetChaLifeTime(Monster224, 292850)
				SetChaLifeTime(Monster225, 292900)
				SetChaLifeTime(Monster226, 292950)
				SetChaLifeTime(Monster227, 293000)
				SetChaLifeTime(Monster228, 293050)
				SetChaLifeTime(Monster229, 293100)
				SetChaLifeTime(Monster230, 293150)
				SetChaLifeTime(Monster231, 293200)
				SetChaLifeTime(Monster232, 293250)
				SetChaLifeTime(Monster233, 293300)
				SetChaLifeTime(Monster234, 293350)
				SetChaLifeTime(Monster235, 293400)
				SetChaLifeTime(Monster236, 293450)
				SetChaLifeTime(Monster237, 293500)
				SetChaLifeTime(Monster238, 293550)
				SetChaLifeTime(Monster239, 293600)
				SetChaLifeTime(Monster240, 293650)
				SetChaLifeTime(Monster241, 293700)
				SetChaLifeTime(Monster242, 293750)
				SetChaLifeTime(Monster243, 293800)
				SetChaLifeTime(Monster244, 293850)
				SetChaLifeTime(Monster245, 293900)
				SetChaLifeTime(Monster246, 293950)
				SetChaLifeTime(Monster247, 294000)
				SetChaLifeTime(Monster248, 294050)
				SetChaLifeTime(Monster249, 294100)
				SetChaLifeTime(Monster250, 294150)
				SetChaLifeTime(Monster251, 294200)
				SetChaLifeTime(Monster252, 294250)
				SetChaLifeTime(Monster253, 294300)
				SetChaLifeTime(Monster254, 294350)
				SetChaLifeTime(Monster255, 294400)
				SetChaLifeTime(Monster256, 294450)
				SetChaLifeTime(Monster257, 294500)
				SetChaLifeTime(Monster258, 294550)
				SetChaLifeTime(Monster259, 294600)
				SetChaLifeTime(Monster260, 294650)
				SetChaLifeTime(Monster261, 294700)
				SetChaLifeTime(Monster262, 294750)
				SetChaLifeTime(Monster263, 294800)
				SetChaLifeTime(Monster264, 294850)
				SetChaLifeTime(Monster265, 294900)
				SetChaLifeTime(Monster266, 294950)
				SetChaLifeTime(Monster267, 295000)
				SetChaLifeTime(Monster268, 295050)
				SetChaLifeTime(Monster269, 295100)
				SetChaLifeTime(Monster270, 295150)
				SetChaLifeTime(Monster271, 295200)
				SetChaLifeTime(Monster272, 295250)
				SetChaLifeTime(Monster273, 295300)
				SetChaLifeTime(Monster274, 295350)
				SetChaLifeTime(Monster275, 295400)
				SetChaLifeTime(Monster276, 295450)
				SetChaLifeTime(Monster277, 295500)
				SetChaLifeTime(Monster278, 295550)
				SetChaLifeTime(Monster279, 295600)
				SetChaLifeTime(Monster280, 295650)
				SetChaLifeTime(Monster281, 295700)
				SetChaLifeTime(Monster282, 295750)
				SetChaLifeTime(Monster283, 295800)
				SetChaLifeTime(Monster284, 295850)
				SetChaLifeTime(Monster285, 295900)
				SetChaLifeTime(Monster286, 295950)
				SetChaLifeTime(Monster287, 296000)
				SetChaLifeTime(Monster288, 296050)
				SetChaLifeTime(Monster289, 296100)
				SetChaLifeTime(Monster290, 296150)
				SetChaLifeTime(Monster291, 296200)
				SetChaLifeTime(Monster292, 296250)
				SetChaLifeTime(Monster293, 296300)
				SetChaLifeTime(Monster294, 296350)
				SetChaLifeTime(Monster295, 296400)
				SetChaLifeTime(Monster296, 296450)
				SetChaLifeTime(Monster297, 296500)
				SetChaLifeTime(Monster298, 296550)
				SetChaLifeTime(Monster299, 296600)
				SetChaLifeTime(Monster300, 296650)
				SetChaLifeTime(Monster301, 296700)
				SetChaLifeTime(Monster302, 296750)
				SetChaLifeTime(Monster303, 296800)
				SetChaLifeTime(Monster304, 296850)
				SetChaLifeTime(Monster305, 296900)
				SetChaLifeTime(Monster306, 296950)
				SetChaLifeTime(Monster307, 297000)
				SetChaLifeTime(Monster308, 297050)
				SetChaLifeTime(Monster309, 297100)
				SetChaLifeTime(Monster310, 297150)
				SetChaLifeTime(Monster311, 297200)
				SetChaLifeTime(Monster312, 297250)
				SetChaLifeTime(Monster313, 297300)
				SetChaLifeTime(Monster314, 297350)
				SetChaLifeTime(Monster315, 297400)
				SetChaLifeTime(Monster316, 297450)
				SetChaLifeTime(Monster317, 297500)
				SetChaLifeTime(Monster318, 297550)
				SetChaLifeTime(Monster319, 297600)
				SetChaLifeTime(Monster320, 297650)
				SetChaLifeTime(Monster321, 297700)
				SetChaLifeTime(Monster322, 297750)
				SetChaLifeTime(Monster323, 297800)
				SetChaLifeTime(Monster324, 297850)
				SetChaLifeTime(Monster325, 297900)
				SetChaLifeTime(Monster326, 297950)
				SetChaLifeTime(Monster327, 298000)
				SetChaLifeTime(Monster328, 298050)
				SetChaLifeTime(Monster329, 298100)
				SetChaLifeTime(Monster330, 298150)
				SetChaLifeTime(Monster331, 298200)
				SetChaLifeTime(Monster332, 298250)
				SetChaLifeTime(Monster333, 298300)
				SetChaLifeTime(Monster334, 298350)
				SetChaLifeTime(Monster335, 298400)
				--GMNotice(Message)
				dreampk_Wave7 = dreampk_Wave7 + 1
			end
		end	
		if Minute >= 40 and Minute < 45 then
			if dreampk_Tick == 300 then
				Notice("Chaos Dream will be closed in 5 minutes - "..Survivor.." Survivor(s) !")
			end
			if dreampk_Tick == 180 then
				Notice("Chaos Dream will be closed in 3 minutes - "..Survivor.." Survivor(s) !")
			end
			if dreampk_Tick == 120 then
				Notice("Chaos Dream will be closed in 2 minutes - "..Survivor.." Survivor(s) !")
			end
			if dreampk_Tick == 60 then
				ScrollNotice("Chaos Dream will be closed in 60 seconds - "..Survivor.." Survivor(s) !")
			end
			dreampk_Tick = dreampk_Tick - 1
		end
	end
end
function map_copy_run_special_dreampk( map_copy )

end

function map_run_dreampk( map )

end
function map_copy_close_dreampk( map_copy )
	ClearAllSubMapCha(map_copy)
	ClearAllSubMapMonster(map_copy)
end
function map_copy_before_close_dreampk( map_copy )
	dreampk_Active_Player = GetMapActivePlayer(map_copy)
	if dreampk_Active_Player > 0 then
		DealAllActivePlayerInMap(map_copy, "ChaosDreamRewards")
	end
	dreampk_Init()
end

function can_open_entry_dreampk( map )
local Hour = GetNowTime()
if Hour == 3 or Hour == 15 then
    return 1  -- Map is open
end
return 0  -- Map is closed

end

function ChaosDreamRewards(Player)
	if dreampk_Active_Player == 0 then
		return
	end
	local Money = math.floor(dreampk_Money/dreampk_Active_Player)
	if dreampk_Active_Player > 5 then
		AddMoney(Player, 0, Money)
		return
	end
	if dreampk_Active_Player <  5 and dreampk_Active_Player > 1 then
	if GetChaFreeBagGridNum(Player) >= 5 then		
			GiveItem(Player, 0, 3457, 5, 4)
			GiveItem(Player, 0, 0854, 3, 4)
			GiveItem(Player, 0, 9941, 1, 4)
			GiveItem(Player, 0, 9612, 1, 4)
		else
			GiveItemX(Player, 0, 3457, 5, 4)
			GiveItemX(Player, 0, 0854, 3, 4)
			GiveItemX(Player, 0, 9941, 1, 4)
			GiveItemX(Player, 0, 9612, 1, 4)
		end
		AddMoney(Player, 0, Money)
		return
	end	
	
	------------------------------------
	if dreampk_Active_Player == 1 then
		if GetChaFreeBagGridNum(Player) >= 6 then
			GiveItem(Player, 0, 3878, 1, 4)
			GiveItem(Player, 0, 9941, 3, 4)
			GiveItem(Player, 0, 9612, 3, 4)	
			GiveItem(Player, 0, 9939, 2, 4)	
			GiveItem(Player, 0, 9989, 1, 4)	
		else
			GiveItemX(Player, 0, 3878, 1, 4)
			GiveItemX(Player, 0, 9941, 3, 4)
			GiveItemX(Player, 0, 9612, 3, 4)
			GiveItemX(Player, 0, 9939, 2, 4)
			GiveItemX(Player, 0, 9989, 1, 4)
		end
		AddMoney(Player, 0, Money)
		ScrollNotice("[Chaos Dream]: Congratulations "..GetChaDefaultName(Player)..", you are the winner of Chaos Dream on this round!",1, 0XFFF6E58D)
		return
	end
end
function dreampkGetReaperPlayer()
    local dreampk_kills = PANEL_PLAYER_KILL_COUNT["dreampk"]
    if not dreampk_kills then
        return "N/A", 0
    end

    local top_player_name = "N/A"
    local most_kills = 0

    for player_name, kills in pairs(dreampk_kills) do
        if kills > most_kills then
            most_kills = kills
            top_player_name = player_name
        end
    end

    return top_player_name, most_kills
end
---- KDR PANEL
function dreampkUpdateKdrPanel(character)
    local map_copy = GetChaMapCopy(character)
    --local survivor = GetMapActivePlayer(map_copy)
    local character_name = GetChaDefaultName(character)

    -- Ensure the "dreampk" map entry exists in PANEL_PLAYER_KILL_COUNT
	PANEL_PLAYER_KILL_COUNT["dreampk"] = PANEL_PLAYER_KILL_COUNT["dreampk"] or {}
	PANEL_PLAYER_DEATH_COUNT["dreampk"] = PANEL_PLAYER_DEATH_COUNT["dreampk"] or {}
	PANEL_LAST_PLAYER_KILLED["dreampk"] = PANEL_LAST_PLAYER_KILLED["dreampk"] or {}

    -- Now safely access the character kills, deaths and last player killed
    local character_kills = PANEL_PLAYER_KILL_COUNT["dreampk"][character_name] or 0
    local character_deaths = PANEL_PLAYER_DEATH_COUNT["dreampk"][character_name] or 0
    local last_player_killed = GetChaDefaultName(PANEL_LAST_PLAYER_KILLED["dreampk"][character_name]) or "N/A"
	local chaos_reaper_player_name, chaos_reaper_kills = dreampkGetReaperPlayer()
	local survivor = GetMapActivePlayer(map_copy)
    local message = "Alive(s): " .. survivor .. "\n\nKill(s) : " .. character_kills .. "\n\nDeath(s): " .. character_deaths .. "\n\nLast Killed: " .. last_player_killed .. "\n\nBest Reaper: ".. chaos_reaper_player_name

    UpdateTeamPointsPanel(character, message)
end

-- dreampkNotice = function(map_copy)
	-- local Message = '[Chaos Dream]: Total Players Alive: '..GetMapActivePlayer(map_copy)
	-- if table.getn(dreampk_GuildLog) ~= 0 then
		-- for GuildID, GuildCount in pairs(dreampk_GuildLog) do
		-- if GuildID == 0 then
			-- Message = Message..'\t [Guildless Player(s)]: '..GuildCount
		-- else
			-- Message = Message..'\t Guild ['..GetGuildName(GuildID)..']: '..GuildCount
		-- end
	-- end
	-- GMNotice(Message)
-- end
-- end