print("------------------------------------")
print("-- Loading snowar file            --")
print("------------------------------------")
print("-- [Loading] ctrl.lua")
function config(map)
	MapCanSavePos(map, 0)			-- 1 = Allow players to save respaw // 0 = Do not allow players to save respaw
	MapCanPK(map, 1)				-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
	MapCopyNum(map, 1)				-- 1 Copy of the map will be generated by GameServer
	SingleMapCopyPlyNum(map, 300)	-- 300 Players are allowed to enter the map
	MapCanTeam(map , 1)				-- 1 = Allow players to create party // 0 = Do not allow players to create party
	MapType(map, 4)					-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )        
    MapCanStall(map, 0)				-- 1 = Allow players to set stall // 0 = Do not allow players to set stall
	ShowInPortalTimer(map, LUA_TRUE, 282,373)
end


function get_map_entry_pos_snowar()
	return 282,373
end

function init_entry(map)
    SetMapEntryMapName(map, "lobbycityafk2")
	--SetMapEntryTime(map, "2006/10/18/10/0", "0/12/0", "0/0/30", "0/0/45")
	SetMapEntryTime(map, "2006/10/18/7/0", "0/12/0", "0/0/30", "0/0/45")
end
function snowar_Init()
    PANEL_PLAYER_KILL_COUNT["snowar"] = {}
    PANEL_PLAYER_DEATH_COUNT["snowar"] = {}
	PANEL_LAST_PLAYER_KILLED["snowar"] = {}
	snowar_Active_Player = 0
	snowar_Money = 10000000
	snowar_Wave1 = 0
	snowar_Wave2 = 0
	snowar_Wave3 = 0
	snowar_Wave4 = 0
	snowar_Wave5 = 0
	snowar_Wave6 = 0
	snowar_Wave7 = 0
	snowar_Tick = 300
	--snowar_GuildLog = {}
end
snowar_Init()

function after_enter_snowar( Player , map_copy )
	Restriction.Add(Player, 'snowar', 'MAC')
	-- local GuildID = GetChaGuildID(Player)
	-- if GuildID ~= 0 then
		-- snowar_GuildLog[GuildID] = snowar_GuildLog[GuildID] or 0
		-- snowar_GuildLog[GuildID] = snowar_GuildLog[GuildID] + 1
	-- else 
		-- snowar_GuildLog[0] = snowar_GuildLog[0] or 0
		-- snowar_GuildLog[0] = snowar_GuildLog[0] + 1
	-- end
end

function before_leave_snowar( Player )
	Notice(GetChaDefaultName(Player)..' has left Snow War!')
	Restriction.Rem(Player, 'snowar', 'MAC')
	--BeforeLeaveZone(Player)
	
	--hide playerpanel out o fca
	UpdateTeamPointsPanel(Player, "hide")
	-- local GuildID = GetChaGuildID(Player)
	-- if GuildID ~= 0 then
		-- snowar_GuildLog[GuildID] = snowar_GuildLog[GuildID] or 0
		-- snowar_GuildLog[GuildID] = snowar_GuildLog[GuildID] - 1
		
		-- if snowar_GuildLog[GuildID] <= 0 then
			-- snowar_GuildLog[GuildID] = nil
		-- end
	-- else 
		-- snowar_GuildLog[0] = snowar_GuildLog[0] or 0
		-- snowar_GuildLog[0] = snowar_GuildLog[0] - 1
		
		-- if snowar_GuildLog[0] <= 0 then
			-- snowar_GuildLog[0] = nil
		-- end
	-- end
end

function map_copy_first_run_snowar(map_copy)
end

function map_copy_run_snowar( map_copy )
	local Survivor = GetMapActivePlayer(map_copy)
	local MapName = "Snow War"
	SetMapEntryEventName(PortalEntryData9.snowar, ""..MapName.." | [ "..Survivor.." ] Survivor(s)")
	local Hour = tonumber(os.date("%H"))
	local Minute = tonumber(os.date("%M"))
	local Second = tonumber(os.date("%S"))
	local Message = "Snow War still have survivor(s): "..Survivor.." player(s)!"
	
	DealAllPlayerInMap(map_copy,"snowarUpdateKdrPanel")
	
	if Hour == 7 or Hour == 19 then
		if Minute == 5 and Second == 0 then
	GMNotice(Message)
		if snowar_Wave1 == 0 then
		local Monster2 = CreateChaEx(859, 9400, 8400, 145, 180,map_copy)
		local Monster3 = CreateChaEx(859, 15700, 9000, 145, 180,map_copy)
		local Monster4 = CreateChaEx(859, 18100, 11100, 145, 180,map_copy)
		local Monster5 = CreateChaEx(859, 11500, 12300, 145, 180,map_copy)
		local Monster6 = CreateChaEx(859, 8000, 16200, 145, 180,map_copy)
		local Monster7 = CreateChaEx(859, 15800, 15800, 145, 180,map_copy)
		local Monster8 = CreateChaEx(859, 12600, 18000, 145, 180,map_copy)
		local Monster9 = CreateChaEx(859, 13000, 20500, 145, 180,map_copy)
		local Monster10 = CreateChaEx(859, 17500, 21000, 145, 180,map_copy)
		local Monster11 = CreateChaEx(859, 7800, 222000, 145, 180,map_copy)
		SetChaLifeTime(Monster2,299050)
		SetChaLifeTime(Monster3,299100)
		SetChaLifeTime(Monster4,299150)
		SetChaLifeTime(Monster5,299200)
		SetChaLifeTime(Monster6,299250)
		SetChaLifeTime(Monster7,299300)
		SetChaLifeTime(Monster8,299350)
		SetChaLifeTime(Monster9,299400)
		SetChaLifeTime(Monster10,299450)
		SetChaLifeTime(Monster11,299500)
		--GMNotice(Message)
		snowar_Wave1 = snowar_Wave1 + 1
	end
		end
	if Minute == 10 and Second == 0 then
	GMNotice(Message)
		if snowar_Wave2 == 0 then
		local Monster12 = CreateChaEx(860, 9400, 8400, 145, 180,map_copy)
		local Monster13 = CreateChaEx(860, 15700, 9000, 145, 180,map_copy)
		local Monster14 = CreateChaEx(860, 18100, 11100, 145, 180,map_copy)
		local Monster15 = CreateChaEx(860, 11500, 12300, 145, 180,map_copy)
		local Monster16 = CreateChaEx(860, 8000, 16200, 145, 180,map_copy)
		local Monster17 = CreateChaEx(860, 15800, 15800, 145, 180,map_copy)
		local Monster18 = CreateChaEx(860, 12600, 18000, 145, 180,map_copy)
		local Monster19 = CreateChaEx(860, 13000, 20500, 145, 180,map_copy)
		local Monster20 = CreateChaEx(860, 17500, 21000, 145, 180,map_copy)
		local Monster21 = CreateChaEx(860, 7800, 222000, 145, 180,map_copy)
		SetChaLifeTime(Monster12, 299050)
		SetChaLifeTime(Monster13, 299100)
		SetChaLifeTime(Monster14, 299150)
		SetChaLifeTime(Monster15, 299200)
		SetChaLifeTime(Monster16, 299250)
		SetChaLifeTime(Monster17, 299300)
		SetChaLifeTime(Monster18, 299350)
		SetChaLifeTime(Monster19, 299400)
		SetChaLifeTime(Monster20, 299450)
		SetChaLifeTime(Monster21, 299500)
		--GMNotice(Message)
		snowar_Wave2 = snowar_Wave2 + 1
			end
	end
	if Minute == 15 and Second == 0 then
	GMNotice(Message)
		if snowar_Wave3 == 0 then
		local Monster22 = CreateChaEx(861, 9400, 8400, 145, 180,map_copy)
		local Monster23 = CreateChaEx(861, 15700, 9000, 145, 180,map_copy)
		local Monster24 = CreateChaEx(861, 18100, 11100, 145, 180,map_copy)
		local Monster25 = CreateChaEx(861, 11500, 12300, 145, 180,map_copy)
		local Monster26 = CreateChaEx(861, 8000, 16200, 145, 180,map_copy)
		local Monster27 = CreateChaEx(861, 15800, 15800, 145, 180,map_copy)
		local Monster28 = CreateChaEx(861, 12600, 18000, 145, 180,map_copy)
		local Monster29 = CreateChaEx(861, 13000, 20500, 145, 180,map_copy)
		local Monster30 = CreateChaEx(861, 17500, 21000, 145, 180,map_copy)
		local Monster31 = CreateChaEx(861, 7800, 222000, 145, 180,map_copy)
		SetChaLifeTime(Monster22, 299050)
		SetChaLifeTime(Monster23, 299100)
		SetChaLifeTime(Monster24, 299150)
		SetChaLifeTime(Monster25, 299200)
		SetChaLifeTime(Monster26, 299250)
		SetChaLifeTime(Monster27, 299300)
		SetChaLifeTime(Monster28, 299350)
		SetChaLifeTime(Monster29, 299400)
		SetChaLifeTime(Monster30, 299450)
		SetChaLifeTime(Monster31, 299500)
		--GMNotice(Message)
		snowar_Wave3 = snowar_Wave3 + 1
			end
	end
	if Minute == 20 and Second == 0 then
	GMNotice(Message)
		if snowar_Wave4 == 0 then
		local Monster32 = CreateChaEx(868, 8100, 8300, 145, 60,map_copy)
		local Monster33 = CreateChaEx(872, 10200, 7100, 145, 60,map_copy)
		local Monster34 = CreateChaEx(875, 11600, 9100, 145, 60,map_copy)
		local Monster35 = CreateChaEx(879, 7600, 11100, 145, 60,map_copy)
		local Monster36 = CreateChaEx(875, 6800, 15600, 145, 60,map_copy)
		local Monster37 = CreateChaEx(879, 14000, 8400, 145, 60,map_copy)
		local Monster38 = CreateChaEx(875, 17000, 8700, 145, 60,map_copy)
		local Monster39 = CreateChaEx(872, 18300, 7700, 145, 60,map_copy)
		local Monster40 = CreateChaEx(879, 18400, 11000, 145, 60,map_copy)
		local Monster41 = CreateChaEx(875, 18200, 13500, 145, 60,map_copy)
		local Monster42 = CreateChaEx(868, 16200, 10400, 145, 60,map_copy)
		local Monster43 = CreateChaEx(879, 14000, 11700, 145, 60,map_copy)
		local Monster44 = CreateChaEx(868, 9700, 13300, 145, 60,map_copy)
		local Monster45 = CreateChaEx(879, 12700, 15100, 145, 60,map_copy)
		local Monster46 = CreateChaEx(872, 10400, 17400, 145, 60,map_copy)
		local Monster47 = CreateChaEx(872, 16900, 16500, 145, 60,map_copy)
		local Monster48 = CreateChaEx(868, 14900, 17700, 145, 60,map_copy)
		local Monster49 = CreateChaEx(872, 7400, 20000, 145, 60,map_copy)
		local Monster50 = CreateChaEx(879, 13000, 19400, 145, 60,map_copy)
		local Monster51 = CreateChaEx(875, 10900, 20700, 145, 60,map_copy)
		local Monster52 = CreateChaEx(868, 9000, 23000, 145, 60,map_copy)
		local Monster53 = CreateChaEx(875, 15200, 20200, 145, 60,map_copy)
		local Monster54 = CreateChaEx(868, 18100, 21100, 145, 60,map_copy)
		local Monster55 = CreateChaEx(872, 15500, 22500, 145, 60,map_copy)
		SetChaLifeTime(Monster32,298050)
		SetChaLifeTime(Monster33,298100)
		SetChaLifeTime(Monster34,298150)
		SetChaLifeTime(Monster35,298200)
		SetChaLifeTime(Monster36,298250)
		SetChaLifeTime(Monster37,298300)
		SetChaLifeTime(Monster38,298350)
		SetChaLifeTime(Monster39,298400)
		SetChaLifeTime(Monster40,298450)
		SetChaLifeTime(Monster41,298500)
		SetChaLifeTime(Monster42,298550)
		SetChaLifeTime(Monster43,298600)
		SetChaLifeTime(Monster44,298650)
		SetChaLifeTime(Monster45,298700)
		SetChaLifeTime(Monster46,298750)
		SetChaLifeTime(Monster47,298800)
		SetChaLifeTime(Monster48,298850)
		SetChaLifeTime(Monster49,298900)
		SetChaLifeTime(Monster50,298950)
		SetChaLifeTime(Monster51,299000)
		SetChaLifeTime(Monster52,299050)
		SetChaLifeTime(Monster53,299100)
		SetChaLifeTime(Monster54,299050)
		SetChaLifeTime(Monster55,299200)
		--GMNotice(Message)
		snowar_Wave4 = snowar_Wave4 + 1
			end
	end
	if Minute == 25 and Second == 0 then
	GMNotice(Message)
		if snowar_Wave5 == 0 then
		local Monster56 = CreateChaEx(869, 8100, 8300, 145, 60,map_copy)
		local Monster57 = CreateChaEx(873, 10200, 7100, 145, 60,map_copy)
		local Monster58 = CreateChaEx(876, 11600, 9100, 145, 60,map_copy)
		local Monster59 = CreateChaEx(880, 7600, 11100, 145, 60,map_copy)
		local Monster60 = CreateChaEx(876, 6800, 15600, 145, 60,map_copy)
		local Monster61 = CreateChaEx(880, 14000, 8400, 145, 60,map_copy)
		local Monster62 = CreateChaEx(876, 17000, 8700, 145, 60,map_copy)
		local Monster63 = CreateChaEx(873, 18300, 7700, 145, 60,map_copy)
		local Monster64 = CreateChaEx(880, 18400, 11000, 145, 60,map_copy)
		local Monster65 = CreateChaEx(876, 18200, 13500, 145, 60,map_copy)
		local Monster66 = CreateChaEx(869, 16200, 10400, 145, 60,map_copy)
		local Monster67 = CreateChaEx(880, 14000, 11700, 145, 60,map_copy)
		local Monster68 = CreateChaEx(869, 9700, 13300, 145, 60,map_copy)
		local Monster69 = CreateChaEx(880, 12700, 15100, 145, 60,map_copy)
		local Monster70 = CreateChaEx(873, 10400, 17400, 145, 60,map_copy)
		local Monster71 = CreateChaEx(873, 16900, 16500, 145, 60,map_copy)
		local Monster72 = CreateChaEx(869, 14900, 17700, 145, 60,map_copy)
		local Monster73 = CreateChaEx(873, 7400, 20000, 145, 60,map_copy)
		local Monster74 = CreateChaEx(880, 13000, 19400, 145, 60,map_copy)
		local Monster75 = CreateChaEx(876, 10900, 20700, 145, 60,map_copy)
		local Monster76 = CreateChaEx(869, 9000, 23000, 145, 60,map_copy)
		local Monster77 = CreateChaEx(876, 15200, 20200, 145, 60,map_copy)
		local Monster78 = CreateChaEx(869, 18100, 21100, 145, 60,map_copy)
		local Monster79 = CreateChaEx(873, 15500, 22500, 145, 60,map_copy)
			SetChaLifeTime(Monster56,297050)
			SetChaLifeTime(Monster57,297100)
			SetChaLifeTime(Monster58,297150)
			SetChaLifeTime(Monster59,297200)
			SetChaLifeTime(Monster60,297250)
			SetChaLifeTime(Monster61,297300)
			SetChaLifeTime(Monster62,297350)
			SetChaLifeTime(Monster63,297400)
			SetChaLifeTime(Monster64,297450)
			SetChaLifeTime(Monster65,297500)
			SetChaLifeTime(Monster66,297550)
			SetChaLifeTime(Monster67,297600)
			SetChaLifeTime(Monster68,297650)
			SetChaLifeTime(Monster69,297700)
			SetChaLifeTime(Monster70,297750)
			SetChaLifeTime(Monster71,297800)
			SetChaLifeTime(Monster72,297850)
			SetChaLifeTime(Monster73,297900)
			SetChaLifeTime(Monster74,297950)
			SetChaLifeTime(Monster75,298000)
			SetChaLifeTime(Monster76,298050)
			SetChaLifeTime(Monster77,298100)
			SetChaLifeTime(Monster78,298150)
			SetChaLifeTime(Monster79,298200)
			--GMNotice(Message)
			snowar_Wave5 = snowar_Wave5 + 1
			end
	end
	if Minute == 30 and Second == 0 then
	GMNotice(Message)
		if snowar_Wave6 == 0 then
		local Monster94 = CreateChaEx(883, 8103, 15758, 145, 60,map_copy)
		local Monster95 = CreateChaEx(884, 6366, 16072, 145, 60,map_copy)
		local Monster96 = CreateChaEx(885, 6158, 14021, 145, 60,map_copy)
		local Monster97 = CreateChaEx(886, 6462, 13205, 145, 60,map_copy)
		local Monster98 = CreateChaEx(884, 18456, 3689, 145, 60,map_copy)
		local Monster99 = CreateChaEx(886, 17992, 3613, 145, 60,map_copy)
		local Monster100 = CreateChaEx(884, 15235, 3295, 145, 60,map_copy)
		local Monster101 = CreateChaEx(885, 11944, 3601, 145, 60,map_copy)
		local Monster102 = CreateChaEx(883, 12378, 3349, 145, 60,map_copy)
		local Monster103 = CreateChaEx(884, 11528, 2721, 145, 60,map_copy)
		local Monster104 = CreateChaEx(884, 9531, 2727, 145, 60,map_copy)
		local Monster105 = CreateChaEx(885, 8534, 3308, 145, 60,map_copy)
		local Monster106 = CreateChaEx(885, 7543, 3164, 145, 60,map_copy)
		local Monster107 = CreateChaEx(886, 6487, 3343, 145, 60,map_copy)
		local Monster108 = CreateChaEx(884, 7192, 4128, 145, 60,map_copy)
		local Monster109 = CreateChaEx(883, 6677, 4895, 145, 60,map_copy)
		local Monster110 = CreateChaEx(885, 6567, 5679, 145, 60,map_copy)
		local Monster111 = CreateChaEx(886, 6701, 6500, 145, 60,map_copy)
		local Monster112 = CreateChaEx(886, 6369, 6949, 145, 60,map_copy)
		local Monster113 = CreateChaEx(884, 6994, 8064, 145, 60,map_copy)
		local Monster114 = CreateChaEx(885, 6505, 8494, 145, 60,map_copy)
		local Monster115 = CreateChaEx(883, 6536, 8923, 145, 60,map_copy)
		local Monster116 = CreateChaEx(883, 6288, 10738, 145, 60,map_copy)
		local Monster117 = CreateChaEx(883, 5901, 12142, 145, 60,map_copy)
		local Monster118 = CreateChaEx(886, 13579, 25098, 145, 60,map_copy)
		local Monster119 = CreateChaEx(885, 12103, 25146, 145, 60,map_copy)
		local Monster120 = CreateChaEx(883, 12122, 24854, 145, 60,map_copy)
		local Monster121 = CreateChaEx(883, 11116, 24702, 145, 60,map_copy)
		local Monster122 = CreateChaEx(883, 10579, 24343, 145, 60,map_copy)
		local Monster123 = CreateChaEx(886, 10968, 23507, 145, 60,map_copy)
		local Monster124 = CreateChaEx(884, 13141, 22546, 145, 60,map_copy)
		local Monster125 = CreateChaEx(885, 13778, 22539, 145, 60,map_copy)
		local Monster126 = CreateChaEx(885, 13259, 21845, 145, 60,map_copy)
		local Monster127 = CreateChaEx(884, 14899, 20929, 145, 60,map_copy)
		local Monster128 = CreateChaEx(886, 14973, 20419, 145, 60,map_copy)
		local Monster129 = CreateChaEx(883, 13247, 19932, 145, 60,map_copy)
		local Monster130 = CreateChaEx(884, 13892, 19399, 145, 60,map_copy)
		local Monster131 = CreateChaEx(886, 13283, 17519, 145, 60,map_copy)
		local Monster132 = CreateChaEx(883, 18412, 20105, 145, 60,map_copy)
		local Monster133 = CreateChaEx(883, 22194, 18012, 145, 60,map_copy)
		local Monster134 = CreateChaEx(883, 21710, 17182, 145, 60,map_copy)
		local Monster135 = CreateChaEx(884, 20408, 17788, 145, 60,map_copy)
		local Monster136 = CreateChaEx(885, 20461, 17339, 145, 60,map_copy)
		local Monster137 = CreateChaEx(886, 19457, 17817, 145, 60,map_copy)
		local Monster138 = CreateChaEx(886, 16343, 15573, 145, 60,map_copy)
		local Monster139 = CreateChaEx(883, 14078, 15726, 145, 60,map_copy)
		local Monster140 = CreateChaEx(883, 12363, 15855, 145, 60,map_copy)
		local Monster141 = CreateChaEx(883, 11589, 13429, 145, 60,map_copy)
		local Monster142 = CreateChaEx(884, 11113, 13869, 145, 60,map_copy)
		local Monster143 = CreateChaEx(886, 10902, 14335, 145, 60,map_copy)
		local Monster144 = CreateChaEx(885, 9309, 12935, 145, 60,map_copy)
		local Monster145 = CreateChaEx(886, 12534, 11209, 145, 60,map_copy)
		local Monster146 = CreateChaEx(884, 12515, 13202, 145, 60,map_copy)
		local Monster147 = CreateChaEx(885, 14479, 14079, 145, 60,map_copy)
		local Monster148 = CreateChaEx(884, 16426, 11297, 145, 60,map_copy)
		local Monster149 = CreateChaEx(885, 16757, 12339, 145, 60,map_copy)
		local Monster150 = CreateChaEx(885, 17115, 12436, 145, 60,map_copy)
		local Monster151 = CreateChaEx(886, 18473, 12565, 145, 60,map_copy)
		local Monster152 = CreateChaEx(886, 20540, 11384, 145, 60,map_copy)
		local Monster153 = CreateChaEx(885, 20235, 10866, 145, 60,map_copy)
		local Monster154 = CreateChaEx(884, 20390, 9764, 145, 60,map_copy)
		local Monster155 = CreateChaEx(883, 19487, 9642, 145, 60,map_copy)
		local Monster156 = CreateChaEx(886, 19063, 7981, 145, 60,map_copy)
		local Monster157 = CreateChaEx(884, 110766, 7827, 145, 60,map_copy)
		local Monster158 = CreateChaEx(885, 19026, 6331, 145, 60,map_copy)
		local Monster159 = CreateChaEx(883, 18459, 5518, 145, 60,map_copy)
		local Monster160 = CreateChaEx(883, 17781, 6160, 145, 60,map_copy)
		local Monster161 = CreateChaEx(883, 15146, 5255, 145, 60,map_copy)
		local Monster162 = CreateChaEx(885, 15722, 6195, 145, 60,map_copy)
		local Monster163 = CreateChaEx(886, 15088, 6729, 145, 60,map_copy)
		local Monster164 = CreateChaEx(884, 15116, 7447, 145, 60,map_copy)
		local Monster165 = CreateChaEx(885, 12657, 8012, 145, 60,map_copy)
		local Monster166 = CreateChaEx(884, 11770, 6209, 145, 60,map_copy)
		local Monster167 = CreateChaEx(883, 10394, 6937, 145, 60,map_copy)
			SetChaLifeTime(Monster94,296050)
			SetChaLifeTime(Monster95,296100)
			SetChaLifeTime(Monster96,296150)
			SetChaLifeTime(Monster97,296200)
			SetChaLifeTime(Monster98,296250)
			SetChaLifeTime(Monster99,296300)
			SetChaLifeTime(Monster100,296350)
			SetChaLifeTime(Monster101,296400)
			SetChaLifeTime(Monster102,296450)
			SetChaLifeTime(Monster103,296500)
			SetChaLifeTime(Monster104,296550)
			SetChaLifeTime(Monster105,296600)
			SetChaLifeTime(Monster106,296650)
			SetChaLifeTime(Monster107,296700)
			SetChaLifeTime(Monster108,296750)
			SetChaLifeTime(Monster109,296800)
			SetChaLifeTime(Monster110,296850)
			SetChaLifeTime(Monster111,296900)
			SetChaLifeTime(Monster112,296950)
			SetChaLifeTime(Monster113,297000)
			SetChaLifeTime(Monster114,297050)
			SetChaLifeTime(Monster115,297100)
			SetChaLifeTime(Monster116,297150)
			SetChaLifeTime(Monster117,297200)
			SetChaLifeTime(Monster118,297250)
			SetChaLifeTime(Monster119,297300)
			SetChaLifeTime(Monster120,297350)
			SetChaLifeTime(Monster121,297400)
			SetChaLifeTime(Monster122,297450)
			SetChaLifeTime(Monster123,297500)
			SetChaLifeTime(Monster124,297550)
			SetChaLifeTime(Monster125,297600)
			SetChaLifeTime(Monster126,297650)
			SetChaLifeTime(Monster127,297700)
			SetChaLifeTime(Monster128,297750)
			SetChaLifeTime(Monster129,297800)
			SetChaLifeTime(Monster130,297850)
			SetChaLifeTime(Monster131,297900)
			SetChaLifeTime(Monster132,297950)
			SetChaLifeTime(Monster133,298000)
			SetChaLifeTime(Monster134,298050)
			SetChaLifeTime(Monster135,298100)
			SetChaLifeTime(Monster136,298150)
			SetChaLifeTime(Monster137,298200)
			SetChaLifeTime(Monster138,298250)
			SetChaLifeTime(Monster139,298300)
			SetChaLifeTime(Monster140,298350)
			SetChaLifeTime(Monster141,298400)
			SetChaLifeTime(Monster142,298450)
			SetChaLifeTime(Monster143,298500)
			SetChaLifeTime(Monster144,298550)
			SetChaLifeTime(Monster145,298600)
			SetChaLifeTime(Monster146,298650)
			SetChaLifeTime(Monster147,298700)
			SetChaLifeTime(Monster148,298750)
			SetChaLifeTime(Monster149,298800)
			SetChaLifeTime(Monster150,2910780)
			SetChaLifeTime(Monster151,298900)
			SetChaLifeTime(Monster152,298950)
			SetChaLifeTime(Monster153,299000)
			SetChaLifeTime(Monster154,299050)
			SetChaLifeTime(Monster155,299100)
			SetChaLifeTime(Monster156,299150)
			SetChaLifeTime(Monster157,299200)
			SetChaLifeTime(Monster158,299250)
			SetChaLifeTime(Monster159,299300)
			SetChaLifeTime(Monster160,299350)
			SetChaLifeTime(Monster161,299400)
			SetChaLifeTime(Monster162,299450)
			SetChaLifeTime(Monster163,299500)
			SetChaLifeTime(Monster164,299550)
			SetChaLifeTime(Monster165,299600)
			SetChaLifeTime(Monster166,299650)
			SetChaLifeTime(Monster167,299700)
			--GMNotice(Message)
			snowar_Wave6 = snowar_Wave6 + 1
			end
	end
	if Minute == 35 and Second == 0 then
	GMNotice(Message)
		if snowar_Wave7 == 0 then
		local Monster168 =CreateChaEx(883, 68, 71, 145, 60,map_copy)
		local Monster169 =CreateChaEx(884, 71, 68, 145, 60,map_copy)
		local Monster170 =CreateChaEx(883, 9115, 8042, 145, 60,map_copy)
		local Monster171 =CreateChaEx(884, 11436, 7740, 145, 60,map_copy)
		local Monster172 =CreateChaEx(886, 8201, 8590, 145, 60,map_copy)
		local Monster173 =CreateChaEx(884, 9210, 22071, 145, 60,map_copy)
		local Monster174 =CreateChaEx(884, 16967, 22831, 100, 60,map_copy)
		local Monster175 =CreateChaEx(883, 18003, 21061, 235, 60,map_copy)
		local Monster176 =CreateChaEx(884, 18305, 15589, 10, 60,map_copy)
		local Monster177 =CreateChaEx(884, 7791, 14993, 70, 60,map_copy)
		local Monster178 =CreateChaEx(885, 13397, 10783, 340, 60,map_copy)
		local Monster179 =CreateChaEx(885, 6849, 6819, 145, 60,map_copy)
		local Monster180 =CreateChaEx(883, 7144, 9232, 145, 60,map_copy)
		local Monster181 =CreateChaEx(884, 284, 509, 145, 60,map_copy)
		local Monster182 =CreateChaEx(883, 7939, 7260, 145, 60,map_copy)
		local Monster183 =CreateChaEx(884, 8185, 11194, 355, 60,map_copy)
		local Monster184 =CreateChaEx(886, 6618, 12245, 340, 60,map_copy)
		local Monster185 =CreateChaEx(885, 8065, 13506, 325, 60,map_copy)
		local Monster186 =CreateChaEx(886, 9233, 14876, 220, 60,map_copy)
		local Monster187 =CreateChaEx(883, 6729, 15659, 235, 60,map_copy)
		local Monster188 =CreateChaEx(884, 6943, 17451, 160, 60,map_copy)
		local Monster189 =CreateChaEx(886, 8245, 16703, 145, 60,map_copy)
		local Monster190 =CreateChaEx(884, 9236, 18695, 115, 60,map_copy)
		local Monster191 =CreateChaEx(884, 7125, 19397, 220, 60,map_copy)
		local Monster192 =CreateChaEx(885, 7029, 20366, 250, 60,map_copy)
		local Monster193 =CreateChaEx(886, 8300, 21581, 145, 60,map_copy)
		local Monster194 =CreateChaEx(883, 7104, 23177, 235, 60,map_copy)
		local Monster195 =CreateChaEx(884, 11047, 22508, 145, 60,map_copy)
		local Monster196 =CreateChaEx(883, 12120, 19945, 145, 60,map_copy)
		local Monster197 =CreateChaEx(884, 13395, 21325, 145, 60,map_copy)
		local Monster198 =CreateChaEx(886, 13305, 23636, 220, 60,map_copy)
		local Monster199 =CreateChaEx(884, 14870, 21363, 235, 60,map_copy)
		local Monster200 =CreateChaEx(883, 15006, 18640, 145, 60,map_copy)
		local Monster201 =CreateChaEx(884, 16444, 11553, 145, 60,map_copy)
		local Monster202 =CreateChaEx(883, 15395, 8470, 145, 60,map_copy)
		local Monster203 =CreateChaEx(884, 14905, 9146, 145, 60,map_copy)
		local Monster204 =CreateChaEx(884, 15951, 9078, 355, 60,map_copy)
		local Monster205 =CreateChaEx(885, 15381, 10021, 145, 60,map_copy)
		local Monster206 =CreateChaEx(886, 10314, 13037, 145, 60,map_copy)
		local Monster207 =CreateChaEx(886, 11545, 15958, 145, 60,map_copy)
		local Monster208 =CreateChaEx(883, 11793, 18653, 145, 60,map_copy)
		local Monster209 =CreateChaEx(883, 13211, 18723, 145, 60,map_copy)
		local Monster210 =CreateChaEx(883, 14214, 16453, 145, 60,map_copy)
		local Monster211 =CreateChaEx(883, 16598, 14245, 145, 60,map_copy)
		local Monster212 =CreateChaEx(885, 17224, 19508, 145, 60,map_copy)
		local Monster213 =CreateChaEx(886, 16758, 15260, 175, 60,map_copy)
		local Monster214 =CreateChaEx(884, 9859, 10410, 25, 60,map_copy)
		local Monster215 =CreateChaEx(883, 11896, 10259, 85, 60,map_copy)
		local Monster216 =CreateChaEx(886, 11154, 11604, 340, 60,map_copy)
		local Monster217 =CreateChaEx(884, 23667, 18360, 295, 60,map_copy)
		local Monster218 =CreateChaEx(883, 13178, 11824, 265, 60,map_copy)
		local Monster219 =CreateChaEx(885, 15014, 13276, 145, 60,map_copy)
		local Monster220 =CreateChaEx(884, 13742, 15229, 145, 60,map_copy)
		local Monster221 =CreateChaEx(886, 9964, 17242, 145, 60,map_copy)
		local Monster222 =CreateChaEx(884, 12829, 13520, 205, 60,map_copy)
		local Monster223 =CreateChaEx(883, 17099, 7274, 220, 60,map_copy)
		local Monster224 =CreateChaEx(885, 17058, 10237, 130, 60,map_copy)
		local Monster225 =CreateChaEx(884, 17010, 16794, 265, 60,map_copy)
		local Monster226 =CreateChaEx(886, 16582, 18119, 235, 60,map_copy)
		local Monster227 =CreateChaEx(884, 16312, 21211, 145, 60,map_copy)
		local Monster228 =CreateChaEx(883, 14695, 19808, 265, 60,map_copy)
		local Monster229 =CreateChaEx(884, 18912, 16135, 175, 60,map_copy)
		local Monster230 =CreateChaEx(885, 19736, 16999, 145, 60,map_copy)
		local Monster231 =CreateChaEx(886, 19740, 16700, 145, 60,map_copy)
		local Monster232 =CreateChaEx(884, 18961, 18673, 145, 60,map_copy)
		local Monster233 =CreateChaEx(885, 18904, 20313, 145, 60,map_copy)
		local Monster234 =CreateChaEx(886, 21648, 20459, 145, 60,map_copy)
		local Monster235 =CreateChaEx(884, 22210, 18066, 145, 60,map_copy)
		local Monster236 =CreateChaEx(883, 22301, 15984, 145, 60,map_copy)
		local Monster237 =CreateChaEx(884, 20626, 18515, 235, 60,map_copy)
		local Monster238 =CreateChaEx(885, 20946, 14221, 145, 60,map_copy)
		local Monster239 =CreateChaEx(886, 23063, 14130, 145, 60,map_copy)
		local Monster240 =CreateChaEx(883, 23735, 20345, 145, 60,map_copy)
		local Monster241 =CreateChaEx(883, 23513, 23014, 145, 60,map_copy)
		local Monster242 =CreateChaEx(884, 21261, 23534, 145, 60,map_copy)
		local Monster243 =CreateChaEx(886, 19474, 23208, 145, 60,map_copy)
		local Monster244 =CreateChaEx(883, 19546, 22211, 145, 60,map_copy)
		local Monster245 =CreateChaEx(884, 21497, 21932, 145, 60,map_copy)
		local Monster246 =CreateChaEx(885, 6555, 14269, 145, 60,map_copy)
		local Monster247 =CreateChaEx(883, 8749, 20367, 145, 60,map_copy)
		local Monster248 =CreateChaEx(884, 9387, 23221, 145, 60,map_copy)
		local Monster249 =CreateChaEx(883, 10137, 6583, 145, 60,map_copy)
		local Monster250 =CreateChaEx(883, 10727, 8329, 145, 60,map_copy)
		local Monster251 =CreateChaEx(884, 12521, 6892, 145, 60,map_copy)
		local Monster252 =CreateChaEx(886, 12633, 8090, 145, 60,map_copy)
		local Monster253 =CreateChaEx(883, 18306, 7007, 145, 60,map_copy)
		local Monster254 =CreateChaEx(884, 17919, 8062, 145, 60,map_copy)
		local Monster255 =CreateChaEx(885, 18241, 9280, 145, 60,map_copy)
		local Monster256 =CreateChaEx(886, 18195, 11142, 145, 60,map_copy)
		local Monster257 =CreateChaEx(883, 18478, 13058, 145, 60,map_copy)
		local Monster258 =CreateChaEx(885, 15415, 7607, 145, 60,map_copy)
		local Monster259 =CreateChaEx(886, 14380, 8470, 145, 60,map_copy)
		local Monster260 =CreateChaEx(884, 14279, 10057, 145, 60,map_copy)
		local Monster261 =CreateChaEx(886, 14500, 11200, 145, 60,map_copy)
		local Monster262 =CreateChaEx(883, 15774, 12103, 145, 60,map_copy)
		local Monster263 =CreateChaEx(886, 15897, 9088, 145, 60,map_copy)
		local Monster264 =CreateChaEx(883, 15927, 9926, 145, 60,map_copy)
		local Monster265 =CreateChaEx(884, 15870, 11318, 145, 60,map_copy)
		local Monster266 =CreateChaEx(885, 16705, 11009, 145, 60,map_copy)
		local Monster267 =CreateChaEx(883, 16991, 10282, 145, 60,map_copy)
		local Monster268 =CreateChaEx(884, 16776, 9390, 100, 60,map_copy)
		local Monster269 =CreateChaEx(885, 16228, 8008, 145, 60,map_copy)
		local Monster270 =CreateChaEx(884, 17340, 5441, 145, 60,map_copy)
		local Monster271 =CreateChaEx(883, 16977, 6826, 250, 60,map_copy)
		local Monster272 =CreateChaEx(884, 17895, 7596, 145, 60,map_copy)
		local Monster273 =CreateChaEx(886, 18350, 9107, 145, 60,map_copy)
		local Monster274 =CreateChaEx(885, 17184, 12038, 145, 60,map_copy)
		local Monster275 =CreateChaEx(885, 17675, 13625, 280, 60,map_copy)
		local Monster276 =CreateChaEx(886, 17292, 14462, 355, 60,map_copy)
		local Monster277 =CreateChaEx(884, 18674, 13972, 250, 60,map_copy)
		local Monster278 =CreateChaEx(883, 18726, 13152, 235, 60,map_copy)
		local Monster279 =CreateChaEx(885, 19140, 11976, 235, 60,map_copy)
		local Monster280 =CreateChaEx(884, 19373, 10749, 205, 60,map_copy)
		local Monster281 =CreateChaEx(886, 19756, 9173, 250, 60,map_copy)
		local Monster282 =CreateChaEx(885, 20326, 10478, 250, 60,map_copy)
		local Monster283 =CreateChaEx(884, 21174, 11534, 280, 60,map_copy)
		local Monster284 =CreateChaEx(886, 21691, 10492, 220, 60,map_copy)
		local Monster285 =CreateChaEx(883, 8797, 15531, 145, 60,map_copy)
		local Monster286 =CreateChaEx(883, 20759, 8953, 235, 60,map_copy)
		local Monster287 =CreateChaEx(883, 19452, 7657, 220, 60,map_copy)
		local Monster288 =CreateChaEx(885, 19486, 6799, 220, 60,map_copy)
		local Monster289 =CreateChaEx(884, 20496, 7737, 145, 60,map_copy)
		local Monster290 =CreateChaEx(883, 20700, 6806, 145, 60,map_copy)
		local Monster291 =CreateChaEx(884, 20642, 5653, 220, 60,map_copy)
		local Monster292 =CreateChaEx(886, 19568, 5521, 220, 60,map_copy)
		local Monster293 =CreateChaEx(886, 18070, 5694, 145, 60,map_copy)
		local Monster294 =CreateChaEx(884, 15987, 6943, 145, 60,map_copy)
		local Monster295 =CreateChaEx(883, 14332, 7074, 145, 60,map_copy)
		local Monster296 =CreateChaEx(885, 13255, 6892, 145, 60,map_copy)
		local Monster297 =CreateChaEx(884, 11828, 7155, 145, 60,map_copy)
		local Monster298 =CreateChaEx(883, 10361, 6896, 175, 60,map_copy)
		local Monster299 =CreateChaEx(885, 9856, 6512, 145, 60,map_copy)
		local Monster300 =CreateChaEx(886, 10510, 5556, 145, 60,map_copy)
		local Monster301 =CreateChaEx(883, 11501, 6188, 145, 60,map_copy)
		local Monster302 =CreateChaEx(884, 12417, 5925, 175, 60,map_copy)
		local Monster303 =CreateChaEx(883, 14962, 6289, 145, 60,map_copy)
		local Monster304 =CreateChaEx(885, 14056, 6124, 145, 60,map_copy)
		local Monster305 =CreateChaEx(884, 15776, 5999, 190, 60,map_copy)
		local Monster306 =CreateChaEx(886, 14497, 4230, 115, 60,map_copy)
		local Monster307 =CreateChaEx(886, 17683, 4209, 250, 60,map_copy)
		local Monster308 =CreateChaEx(883, 19524, 4054, 220, 60,map_copy)
		local Monster309 =CreateChaEx(886, 19698, 3217, 160, 60,map_copy)
		local Monster310 =CreateChaEx(883, 19010, 3462, 145, 60,map_copy)
		local Monster311 =CreateChaEx(884, 17617, 3373, 145, 60,map_copy)
		local Monster312 =CreateChaEx(885, 16722, 2757, 145, 60,map_copy)
		local Monster313 =CreateChaEx(886, 15852, 3275, 145, 60,map_copy)
		local Monster314 =CreateChaEx(883, 15111, 3340, 145, 60,map_copy)
		local Monster315 =CreateChaEx(884, 14381, 2672, 145, 60,map_copy)
		local Monster316 =CreateChaEx(885, 13548, 3291, 145, 60,map_copy)
		local Monster317 =CreateChaEx(883, 12330, 2930, 145, 60,map_copy)
		local Monster318 =CreateChaEx(884, 11616, 3663, 145, 60,map_copy)
		local Monster319 =CreateChaEx(885, 10642, 2901, 145, 60,map_copy)
		local Monster320 =CreateChaEx(886, 10180, 4087, 145, 60,map_copy)
		local Monster321 =CreateChaEx(883, 9541, 3296, 145, 60,map_copy)
		local Monster322 =CreateChaEx(884, 9087, 3095, 145, 60,map_copy)
		local Monster323 =CreateChaEx(883, 8476, 3854, 145, 60,map_copy)
		local Monster324 =CreateChaEx(885, 7821, 3114, 145, 60,map_copy)
		local Monster325 =CreateChaEx(886, 6536, 4350, 145, 60,map_copy)
		local Monster326 =CreateChaEx(885, 7257, 5414, 115, 60,map_copy)
		local Monster327 =CreateChaEx(884, 7122, 7119, 145, 60,map_copy)
		local Monster328 =CreateChaEx(883, 7189, 10782, 145, 60,map_copy)
		local Monster329 =CreateChaEx(884, 7165, 11359, 145, 60,map_copy)
		local Monster330 =CreateChaEx(885, 7175, 13327, 100, 60,map_copy)
		local Monster331 =CreateChaEx(886, 7096, 15693, 70, 60,map_copy)
		local Monster332 =CreateChaEx(885, 6836, 3723, 145, 60,map_copy)
		local Monster333 =CreateChaEx(885, 21369, 9546, 205, 60,map_copy)
		local Monster334 =CreateChaEx(1844, 10600, 9775, 205, 60,map_copy)
			SetChaLifeTime(Monster168,290050)
			SetChaLifeTime(Monster169,290100)
			SetChaLifeTime(Monster170,290150)
			SetChaLifeTime(Monster171,290200)
			SetChaLifeTime(Monster172,290250)
			SetChaLifeTime(Monster173,290300)
			SetChaLifeTime(Monster174,290350)
			SetChaLifeTime(Monster175,290400)
			SetChaLifeTime(Monster176,290450)
			SetChaLifeTime(Monster177,290500)
			SetChaLifeTime(Monster178,290550)
			SetChaLifeTime(Monster179,290600)
			SetChaLifeTime(Monster180,290650)
			SetChaLifeTime(Monster181,290700)
			SetChaLifeTime(Monster182,290750)
			SetChaLifeTime(Monster183,290800)
			SetChaLifeTime(Monster184,290850)
			SetChaLifeTime(Monster185,290900)
			SetChaLifeTime(Monster186,290950)
			SetChaLifeTime(Monster187,291000)
			SetChaLifeTime(Monster188,291050)
			SetChaLifeTime(Monster189,291100)
			SetChaLifeTime(Monster190,291150)
			SetChaLifeTime(Monster191,291200)
			SetChaLifeTime(Monster192,291250)
			SetChaLifeTime(Monster193,291300)
			SetChaLifeTime(Monster194,291350)
			SetChaLifeTime(Monster195,291400)
			SetChaLifeTime(Monster196,291450)
			SetChaLifeTime(Monster197,291500)
			SetChaLifeTime(Monster198,291550)
			SetChaLifeTime(Monster199,291600)
			SetChaLifeTime(Monster200,291650)
			SetChaLifeTime(Monster201,291700)
			SetChaLifeTime(Monster202,291750)
			SetChaLifeTime(Monster203,291800)
			SetChaLifeTime(Monster204,291850)
			SetChaLifeTime(Monster205,291900)
			SetChaLifeTime(Monster206,291950)
			SetChaLifeTime(Monster207,292000)
			SetChaLifeTime(Monster208,292050)
			SetChaLifeTime(Monster209,292100)
			SetChaLifeTime(Monster210,292150)
			SetChaLifeTime(Monster211,292200)
			SetChaLifeTime(Monster212,292250)
			SetChaLifeTime(Monster213,292300)
			SetChaLifeTime(Monster214,292350)
			SetChaLifeTime(Monster215,292400)
			SetChaLifeTime(Monster216,292450)
			SetChaLifeTime(Monster217,292500)
			SetChaLifeTime(Monster218,292550)
			SetChaLifeTime(Monster219,292600)
			SetChaLifeTime(Monster220,292650)
			SetChaLifeTime(Monster221,292700)
			SetChaLifeTime(Monster222,292750)
			SetChaLifeTime(Monster223,292800)
			SetChaLifeTime(Monster224,292850)
			SetChaLifeTime(Monster225,292900)
			SetChaLifeTime(Monster226,292950)
			SetChaLifeTime(Monster227,293000)
			SetChaLifeTime(Monster228,293050)
			SetChaLifeTime(Monster229,293100)
			SetChaLifeTime(Monster230,293150)
			SetChaLifeTime(Monster231,293200)
			SetChaLifeTime(Monster232,293250)
			SetChaLifeTime(Monster233,293300)
			SetChaLifeTime(Monster234,293350)
			SetChaLifeTime(Monster235,293400)
			SetChaLifeTime(Monster236,293450)
			SetChaLifeTime(Monster237,293500)
			SetChaLifeTime(Monster238,293550)
			SetChaLifeTime(Monster239,293600)
			SetChaLifeTime(Monster240,293650)
			SetChaLifeTime(Monster241,293700)
			SetChaLifeTime(Monster242,293750)
			SetChaLifeTime(Monster243,293800)
			SetChaLifeTime(Monster244,293850)
			SetChaLifeTime(Monster245,293900)
			SetChaLifeTime(Monster246,293950)
			SetChaLifeTime(Monster247,294000)
			SetChaLifeTime(Monster248,294050)
			SetChaLifeTime(Monster249,294100)
			SetChaLifeTime(Monster250,294150)
			SetChaLifeTime(Monster251,294200)
			SetChaLifeTime(Monster252,294250)
			SetChaLifeTime(Monster253,294300)
			SetChaLifeTime(Monster254,294350)
			SetChaLifeTime(Monster255,294400)
			SetChaLifeTime(Monster256,294450)
			SetChaLifeTime(Monster257,294500)
			SetChaLifeTime(Monster258,294550)
			SetChaLifeTime(Monster259,294600)
			SetChaLifeTime(Monster260,294650)
			SetChaLifeTime(Monster261,294700)
			SetChaLifeTime(Monster262,294750)
			SetChaLifeTime(Monster263,294800)
			SetChaLifeTime(Monster264,294850)
			SetChaLifeTime(Monster265,294900)
			SetChaLifeTime(Monster266,294950)
			SetChaLifeTime(Monster267,295000)
			SetChaLifeTime(Monster268,295050)
			SetChaLifeTime(Monster269,295100)
			SetChaLifeTime(Monster270,295150)
			SetChaLifeTime(Monster271,295200)
			SetChaLifeTime(Monster272,295250)
			SetChaLifeTime(Monster273,295300)
			SetChaLifeTime(Monster274,295350)
			SetChaLifeTime(Monster275,295400)
			SetChaLifeTime(Monster276,295450)
			SetChaLifeTime(Monster277,295500)
			SetChaLifeTime(Monster278,295550)
			SetChaLifeTime(Monster279,295600)
			SetChaLifeTime(Monster280,295650)
			SetChaLifeTime(Monster281,295700)
			SetChaLifeTime(Monster282,295750)
			SetChaLifeTime(Monster283,295800)
			SetChaLifeTime(Monster284,295850)
			SetChaLifeTime(Monster285,295900)
			SetChaLifeTime(Monster286,295950)
			SetChaLifeTime(Monster287,296000)
			SetChaLifeTime(Monster288,296050)
			SetChaLifeTime(Monster289,296100)
			SetChaLifeTime(Monster290,296150)
			SetChaLifeTime(Monster291,296200)
			SetChaLifeTime(Monster292,296250)
			SetChaLifeTime(Monster293,296300)
			SetChaLifeTime(Monster294,296350)
			SetChaLifeTime(Monster295,296400)
			SetChaLifeTime(Monster296,296450)
			SetChaLifeTime(Monster297,296500)
			SetChaLifeTime(Monster298,296550)
			SetChaLifeTime(Monster299,296600)
			SetChaLifeTime(Monster300,296650)
			SetChaLifeTime(Monster301,296700)
			SetChaLifeTime(Monster302,296750)
			SetChaLifeTime(Monster303,296800)
			SetChaLifeTime(Monster304,296850)
			SetChaLifeTime(Monster305,296900)
			SetChaLifeTime(Monster306,296950)
			SetChaLifeTime(Monster307,297000)
			SetChaLifeTime(Monster308,297050)
			SetChaLifeTime(Monster309,297100)
			SetChaLifeTime(Monster310,297150)
			SetChaLifeTime(Monster311,297200)
			SetChaLifeTime(Monster312,297250)
			SetChaLifeTime(Monster313,297300)
			SetChaLifeTime(Monster314,297350)
			SetChaLifeTime(Monster315,297400)
			SetChaLifeTime(Monster316,297450)
			SetChaLifeTime(Monster317,297500)
			SetChaLifeTime(Monster318,297550)
			SetChaLifeTime(Monster319,297600)
			SetChaLifeTime(Monster320,297650)
			SetChaLifeTime(Monster321,297700)
			SetChaLifeTime(Monster322,297750)
			SetChaLifeTime(Monster323,297800)
			SetChaLifeTime(Monster324,297850)
			SetChaLifeTime(Monster325,297900)
			SetChaLifeTime(Monster326,297950)
			SetChaLifeTime(Monster327,298000)
			SetChaLifeTime(Monster328,298050)
			SetChaLifeTime(Monster329,298100)
			SetChaLifeTime(Monster330,298150)
			SetChaLifeTime(Monster331,298200)
			SetChaLifeTime(Monster332,298250)
			SetChaLifeTime(Monster333,298300)
			SetChaLifeTime(Monster334,298350)
			--GMNotice(Message)
			snowar_Wave7 = snowar_Wave7 + 1
		end
	end
	if Minute >= 40 and Minute < 45 then
			if snowar_Tick == 300 then
				Notice("Snow War will be closed in 5 minutes - "..Survivor.." Survivor(s) !")
			end
			if snowar_Tick == 180 then
				Notice("Snow War will be closed in 3 minutes - "..Survivor.." Survivor(s) !")
			end
			if snowar_Tick == 120 then
				Notice("Snow War will be closed in 2 minutes - "..Survivor.." Survivor(s) !")
			end
			if snowar_Tick == 60 then
				ScrollNotice("Snow War will be closed in 60 seconds - "..Survivor.." Survivor(s) !",1, 0XFFF6E58D)
			end
			snowar_Tick = snowar_Tick - 1
		end
	end
end


function map_copy_run_special_snowar( map_copy ) 
	
end

function map_run_snowar( map )
	
end
function map_copy_close_snowar( map_copy )
	ClearAllSubMapCha(map_copy)
	ClearAllSubMapMonster(map_copy)
end

function map_copy_before_close_snowar( map_copy )
	snowar_Active_Player = GetMapActivePlayer(map_copy)
	if snowar_Active_Player > 0 then
		DealAllActivePlayerInMap(map_copy, "snowarRewards")
	end
	snowar_Init()
end

function can_open_entry_snowar( map ) 
local Hour = GetNowTime()
if Hour == 7 or Hour == 19 then
    return 1  -- Map is open
end
return 0  -- Map is closed
end 

function snowarRewards(Player)
	if snowar_Active_Player == 0 then
		return
	end
	local Money = math.floor(snowar_Money/snowar_Active_Player)
	if snowar_Active_Player > 5 then
		AddMoney(Player, 0, Money)
		return
	end
	if snowar_Active_Player <  5 and snowar_Active_Player > 1 then
		if GetChaFreeBagGridNum(Player) >= 5 then
			GiveItem(Player, 0, 3457, 5, 4)-- Kal Runestones
			GiveItem(Player, 0, 0854, 3, 4)-- 1 Million Dollar Note
			GiveItem(Player, 0, 9941, 1, 4)-- Random Azrael Gem
			GiveItem(Player, 0, 9612, 1, 4)-- Great Gem Pack
		else
			GiveItemX(Player, 0, 3457, 5, 4)
			GiveItemX(Player, 0, 0854, 3, 4)
			GiveItemX(Player, 0, 9941, 1, 4)
			GiveItemX(Player, 0, 9612, 1, 4)
		end
		AddMoney(Player, 0, Money)
		return
	end
	if snowar_Active_Player == 1 then
		if GetChaFreeBagGridNum(Player) >= 6 then
			GiveItem(Player, 0, 3878, 1, 4)		--Chest of Kal Runestone
			GiveItem(Player, 0, 9941, 3, 4)		--Random Azrael Gem Chest
			GiveItem(Player, 0, 9612, 3, 4)		--Great Gem Pack
			GiveItem(Player, 0, 9939, 2, 4)	
			GiveItem(Player, 0, 9989, 1, 4)	
		else
			GiveItemX(Player, 0, 3878, 1, 4)
			GiveItemX(Player, 0, 9941, 3, 4)
			GiveItemX(Player, 0, 9612, 3, 4)
			GiveItemX(Player, 0, 9939, 2, 4)	
			GiveItemX(Player, 0, 9989, 1, 4)
		end
		AddMoney(Player, 0, Money)
		ScrollNotice("[Snow War]: Congratulations "..GetChaDefaultName(Player)..", you are the winner of Snow War on this round!",1, 0XFFF6E58D)
	return	
	end
end
-- at end of ctrl.lua
function snowarGetReaperPlayer()
    local snowar_kills = PANEL_PLAYER_KILL_COUNT["snowar"]
    if not snowar_kills then
        return "N/A", 0
    end

    local top_player_name = "N/A"
    local most_kills = 0

    for player_name, kills in pairs(snowar_kills) do
        if kills > most_kills then
            most_kills = kills
            top_player_name = player_name
        end
    end

    return top_player_name, most_kills
end
function snowarUpdateKdrPanel(character)
    local map_copy = GetChaMapCopy(character)
	local character_name = GetChaDefaultName(character)

    -- Ensure the "snowar" map entry exists in PANEL_PLAYER_KILL_COUNT
	PANEL_PLAYER_KILL_COUNT["snowar"] = PANEL_PLAYER_KILL_COUNT["snowar"] or {}
	PANEL_PLAYER_DEATH_COUNT["snowar"] = PANEL_PLAYER_DEATH_COUNT["snowar"] or {}
	PANEL_LAST_PLAYER_KILLED["snowar"] = PANEL_LAST_PLAYER_KILLED["snowar"] or {}

    -- Now safely access the character kills, deaths and last player killed
    local character_kills = PANEL_PLAYER_KILL_COUNT["snowar"][character_name] or 0
    local character_deaths = PANEL_PLAYER_DEATH_COUNT["snowar"][character_name] or 0
    local last_player_killed = GetChaDefaultName(PANEL_LAST_PLAYER_KILLED["snowar"][character_name]) or "N/A"
	local chaos_reaper_player_name, chaos_reaper_kills = snowarGetReaperPlayer()
	local survivor = GetMapActivePlayer(map_copy)
    
    local message = "Alive(s): " .. survivor .. "\n\nKill(s) : " .. character_kills .. "\n\nDeath(s): " .. character_deaths .. "\n\nLast Killed: " .. last_player_killed .. "\n\nBest Reaper: ".. chaos_reaper_player_name

    UpdateTeamPointsPanel(character, message)
end
-- snowarNotice = function(map_copy)
	-- local Message = '[Snow War]: Total Players Alive: '..GetMapActivePlayer(map_copy)
	-- if table.getn(snowar_GuildLog) ~= 0 then
		-- for GuildID, GuildCount in pairs(snowar_GuildLog) do
		-- if GuildID == 0 then
			-- Message = Message..'\t [Guildless Player(s)]: '..GuildCount
		-- else
			-- Message = Message..'\t Guild ['..GetGuildName(GuildID)..']: '..GuildCount
		-- end
	-- end
	-- GMNotice(Message)
-- end
-- end