print("------------------------------------")
print("-- Loading hell3 file             --")
print("------------------------------------")
print("-- [Loading] ctrl.lua")

function config(map)
	MapCanSavePos(map, 0)			-- 1 = Allow players to save respawn // 0 = Do not allow players to save respawn
	MapCanPK(map, 1)				-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
	MapCopyNum(map, 1)				-- 1 Copy of the map will be generated by GameServer
	SingleMapCopyPlyNum(map, 300)	-- 300 Players are allowed to enter the map
	MapCanTeam(map, 1)				-- 1 = Allow players to create party // 0 = Do not allow players to create party
	MapType(map, 4)					-- PvP settings
    MapCanStall(map, 0)				-- 1 = Allow players to set stall // 0 = Do not allow players to set stall
end

function get_map_entry_pos_hell3()
	return 245, 75
end

function init_entry(map)
	SetMapEntryMapName(map, "hell2")
	SetMapEntryTime(map, "2006/10/18/6/0", "0/12/0", "0/0/60", "0/0/60") -- official
end

function after_enter_hell3(role, map_copy)
	SystemNotice(role, "Mysterious voice: "..GetChaDefaultName(role)..", this is your last stop and also your place of burial. Enjoy your last moments while you can!") 
end

function before_leave_hell3(role)
end

function map_copy_first_run_hell3(map_copy)
end

function map_copy_run_hell3(map_copy)
	-- Check for monster deaths and handle notifications
	if CheckMonsterDead(AZRAEL[10]) == 1 and CRY[10] == 0 then
		MapCopyNotice(map_copy, "Phantom Baron: How can a mortal win my Phantom Sword! What is happening!")
		CRY[10] = 1
	end

	if CheckMonsterDead(AZRAEL[11]) == 1 and CRY[11] == 0 then
		MapCopyNotice(map_copy, "Demon Flame: This icy feeling is the feeling of death?")
		CRY[11] = 1
	end

	if CheckMonsterDead(AZRAEL[12]) == 1 and CRY[12] == 0 then
		MapCopyNotice(map_copy, "Evil Beast: My strength is being drained! No! I do not wish to be defeated!")
		CRY[12] = 1
	end

	if CheckMonsterDead(AZRAEL[13]) == 1 and CRY[13] == 0 then
		MapCopyNotice(map_copy, "Tyran: So this is what it feels to be pierced in the heart?")
		CRY[13] = 1
	end

	if CheckMonsterDead(AZRAEL[14]) == 1 and CRY[14] == 0 then
		MapCopyNotice(map_copy, "Phoenix: The death of a phoenix is only a beginning!")
		CRY[14] = 1
	end

	if CheckMonsterDead(AZRAEL[15]) == 1 and CRY[15] == 0 then
		MapCopyNotice(map_copy, "Despair: Is it that I shouldn't have betrayed Goddess?")
		CRY[15] = 1
	end

	if CheckMonsterDead(AZRAEL[16]) == 1 and CRY[16] == 0 then
		MapCopyNotice(map_copy, "Drakan: Supreme Lord and Harbourer of eternal life.")
		CRY[16] = 1
	end

	if CheckMonsterDead(AZRAEL[17]) == 1 and CRY[17] == 0 then
		MapCopyNotice(map_copy, "Tidal: Red! Why can't my blood be as blue as the sea that I love!")
		CRY[17] = 1
	end
end

function map_copy_run_special_hell3(map)
end

function map_run_hell3(map)
end

function map_copy_close_hell3(map_copy)
	ClearAllSubMapCha(map_copy)
	--ClearAllSubMapMonster(map_copy)
end

function map_copy_before_close_hell3(map_copy)
end

function can_open_entry_hell3(map)
local Hour = GetNowTime()
if Hour == 6 or Hour == 18 then
    return 1  -- Map is open
end
return 0  -- Map is closed
end
