print("------------------------------------")
print("-- Loading puzzleworld2 file      --")
print("------------------------------------")
print("-- [Loading] ctrl.lua" )

function config(map)
	MapCanSavePos(map, 0)			-- 1 = Allow players to save respaw // 0 = Do not allow players to save respaw
	MapCanPK(map, 1)				-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
	MapCopyNum(map, 1)				-- 1 Copy of the map will be generated by GameServer
	SingleMapCopyPlyNum(map, 300)	-- 300 Players are allowed to enter the map
	MapCanTeam(map , 1)				-- 1 = Allow players to create party // 0 = Do not allow players to create party
	MapType(map, 4)					-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )        
    MapCanStall(map, 0)				-- 1 = Allow players to set stall // 0 = Do not allow players to set stall
	--ShowInPortalTimer(map, LUA_TRUE, 239,249)
end

function get_map_entry_pos_puzzleworld2()
	local pos_x = 239
	local pos_y = 249
	return pos_x,pos_y
end

function init_entry(map)
    SetMapEntryMapName(map, "puzzleworld")
     --SetMapEntryTime(map, "2005/8/30/6/0", "0/4/0", "0/0/45", "0/0/120") -- official
	 SetMapEntryTime(map, "2005/8/30/2/0", "0/3/0", "0/0/45", "0/0/120") -- official
end

function after_enter_puzzleworld2(Player, map_copy)
end

function before_leave_puzzleworld2(Player)
end

function map_copy_first_run_puzzleworld2(map_copy)
end

function map_copy_run_puzzleworld2(map_copy)

end

function map_copy_run_special_puzzleworld2(map)
end

function map_run_puzzleworld2(map)
end

function map_copy_close_puzzleworld2(map_copy)
end

function map_copy_before_close_puzzleworld2(map_copy)
end

function can_open_entry_puzzleworld2(map)
local Hour = GetNowTime()
-- Check if the current hour is one of the specified hours: 2, 5, 8, 11 (AM or PM)
if Hour == 2 or Hour == 5 or Hour == 8 or Hour == 11 or 
   Hour == 14 or Hour == 17 or Hour == 20 or Hour == 23 then
    return 1
end

return 0

end