print("------------------------------------")
print("-- Loading hell5 file             --")
print("------------------------------------")
print("-- [Loading] ctrl.lua")

function config(map)
    MapCanSavePos(map, 0)          -- 1 = Allow players to save respawn // 0 = Do not allow players to save respawn
    MapCanPK(map, 1)               -- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
    MapCopyNum(map, 1)             -- 1 Copy of the map will be generated by GameServer
    SingleMapCopyPlyNum(map, 300)  -- 300 Players are allowed to enter the map
    MapCanTeam(map, 1)             -- 1 = Allow players to create party // 0 = Do not allow players to create party
    MapType(map, 4)                -- PvP settings
    MapCanStall(map, 0)            -- 1 = Allow players to set stall // 0 = Do not allow players to set stall
end

function get_map_entry_pos_hell5()
    return 55, 33
end

function init_entry(map)
    SetMapEntryMapName(map, "hell4")
	SetMapEntryTime(map, "2006/10/18/6/0", "0/12/0", "0/0/60", "0/0/60") -- official
end

function after_enter_hell5(Player, map_copy)
    SystemNotice(Player, "Mysterious Voice: " .. GetChaDefaultName(Player) .. ", come and join me. I'm hoping to see what a human can grow to become!")
end

function before_leave_hell5(Player)
end

function map_copy_first_run_hell5(map_copy)
end

function map_copy_run_hell5(map_copy)
    if CheckMonsterDead(AZRAEL[19]) == 1 then
        if CRY[19] == 0 then
            local Notice_all = "Abyss Supreme: Imbecile mortal! Killing me does not change anything! There will always be greed, despair and misery! I will be back one day! Haha!"
            Notice(Notice_all)
            CRY[19] = 1
            BOSSXYSJ[988] = 4    
            BOSSSJSJ[988] = 4    
            BOSSTJSJ[988] = 4    
            BOSSXZSJ[988] = 4    
            BOSSAYSJ[988] = 4
        end
    end

    if CRY[19] == 1 then
        -- Removed HELLCLOSETIME related code
    end
end

function map_copy_run_special_hell5(map)
end

function map_run_hell5(map)
end

function map_copy_close_hell5(map_copy)
ClearAllSubMapCha(map_copy)
--ClearAllSubMapMonster(map_copy)
end

function map_copy_before_close_hell5(map_copy)
end

function can_open_entry_hell5(map)
local Hour = GetNowTime()
if Hour == 6 or Hour == 18 then
    return 1  -- Map is open
end
return 0  -- Map is closed
end
