print("------------------------------------")
print("-- Loading hell file              --")
print("------------------------------------")
print("-- [Loading] ctrl.lua")
function config(map)
	MapCanSavePos(map, 0)			-- 1 = Allow players to save respawn // 0 = Do not allow players to save respawn
	MapCanPK(map, 1)				-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
	MapCopyNum(map, 1)				-- 1 Copy of the map will be generated by GameServer
	SingleMapCopyPlyNum(map, 300)	-- 300 Players are allowed to enter the map
	MapCanTeam(map, 1)				-- 1 = Allow players to create party // 0 = Do not allow players to create party
	MapType(map, 4)					-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )        
    MapCanStall(map, 0)				-- 1 = Allow players to set stall // 0 = Do not allow players to set stall
	--ShowInPortalTimer(map, LUA_TRUE, 199,941)
end

function get_map_entry_pos_hell()
	return 199,941
end

function init_entry(map)
	SetMapEntryMapName(map, "jialebi")
	SetMapEntryTime(map, "2006/10/18/6/0", "0/12/0", "0/0/60", "0/0/60") -- official
end

function after_enter_hell(role, map_copy)
	SystemNotice(role, "Mysterious Voice: "..GetChaDefaultName(role)..", you have invaded my realm of death, my pets will rip you apart mercilessly!") 
end

function before_leave_hell(role)
end

function map_copy_first_run_hell(map_copy)
end

function map_copy_run_hell(map_copy)
	if CheckMonsterDead(AZRAEL[5]) == 1 then
		if CRY[5] == 0 then
			local Notice_all = "Saro: This feeling of suffering is the power of Despair. I'll revive and you all will fall into depths more deeper than despair!!!"
			MapCopyNotice(map_copy, Notice_all)
			CRY[5] = 1
		end
	end
		
	if CheckMonsterDead(AZRAEL[6]) == 1 then
		if CRY[6] == 0 then
			local Notice_all = "Karu: You might have passed this stage, but prepare for the worst!"
			MapCopyNotice(map_copy, Notice_all)
			CRY[6] = 1
		end
	end

	if CheckMonsterDead(AZRAEL[7]) == 1 then
		if CRY[7] == 0 then
			local Notice_all = "Aruthur: I...I was defeated...Please let me off my lord! I do not want to return to damnation!"
			MapCopyNotice(map_copy, Notice_all)
			CRY[7] = 1
		end
	end

	if CheckMonsterDead(AZRAEL[8]) == 1 then
		if CRY[8] == 0 then
			local Notice_all = "Sacrois: Foolish humans, Death has bestowed upon us the gift of immortality. We will meet again! Haha! Haha!"
			MapCopyNotice(map_copy, Notice_all)
			CRY[8] = 1
		end
	end
end

function map_copy_run_special_hell(map)
end

function map_run_hell(map)
end

function map_copy_close_hell(map_copy)
	ClearAllSubMapCha(map_copy)
end

function map_copy_before_close_hell(map_copy)
end

function can_open_entry_hell(map)
local Hour = GetNowTime()
if Hour == 6 or Hour == 18 then
    return 1  -- Map is open
end
return 0  -- Map is closed
end
