function config(map)
    MapCanSavePos(map, 0)		-- 1 = Allow players to save respaw // 0 = Do not allow players to save respaw
    MapCanPK(map, 1)			-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
    MapCopyNum(map, 1)			-- 1 Copy of the map will be generated by GameServer
    SingleMapCopyPlyNum(map, 300)	-- 300 Players are allowed to enter the map
    MapCanTeam(map , 1)			-- 1 = Allow players to create party // 0 = Do not allow players to create party
    MapType ( map , 1 )			-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )        
end

function get_map_entry_pos_volcanoisle()

	local POS_X=2027
	local POS_Y=2731
	return POS_X , POS_Y
	
end

function init_entry(map)
    SetMapEntryMapName(map, "magicsea")
    SetMapEntryTime(map, "2013/10/18/1/0", "0/0/0", "0/0/0", "0/0/0")    
end

function after_enter_volcanoisle( role , map_copy )
Notice("<"..GetChaDefaultName(role).."> hunting in volcano...")
end

function map_copy_run_volcanoisle(map_copy)end
function map_run_volcanoisle(map)end